name: 'Report image sizes'
description: 'Comment image size changes on the PR and update the baseline on master pushes'
inputs:
  sizes-path:
    description: 'Path to the image-sizes.json file produced by the build'
    required: true
  sha:
    description: 'SHA of the commit (used for Docker Hub links)'
    required: true
  title:
    description: 'Title of the comment section'
    required: true
  token:
    description: 'GitHub token for commenting and baseline branch operations'
    required: true
runs:
  using: 'node24'
  main: 'dist/index.js'
