name: 'Report image sizes'
description: 'Comment any changes in image sizes on the PR'
inputs:
  images:
    description: 'Which images to check'
    required: true
  sha:
    description: 'SHA of the commit'
    required: true
  title:
    description: 'Title of the comment'
    required: true
  token:
    description: 'GitHub token to use for commenting'
  docker_username:
    description: 'Docker Hub username for authenticated API requests (increases rate limits)'
  docker_password:
    description: 'Docker Hub password or access token for authenticated API requests'
runs:
  using: 'node24'
  main: 'dist/index.js'
