# labeler cannot label PRs by title: https://github.com/actions/labeler/issues/55
autolabeler:
  - label: 'bug'
    title:
      - '/fix/i'
      - '/bug/i'
      - '/correctly/i'
      - '/use correct/i'
  - label: 'chore'
    title:
      - '/upgrade/i'
  - label: 'enhancement'
    title:
      - '/improve/i'
      - '/enhance/i'
      - '/refine/i'
  - label: 'feature'
    title:
      - '/add support/i'
