version: v1

labels:
  - label: 'bug-fix'
    sync: false
    matcher:
      # no case-insensitive flag (https://github.com/fuxingloh/multi-labeler/issues/341)
      title: '.*(fix|Fix|bug |Bug |correctly|Correctly|use correct|Use correct).*'
  - label: 'chore'
    sync: false
    matcher:
      title: '.*(upgrade|Upgrade).*'
  - label: 'enhancement'
    sync: false
    matcher:
      title: '.*(improve|Improve|enhance|Enhance|refine|Refine|add support|Add support).*'
