version: v1

labels:
  - label: 'bug'
    sync: true
    matcher:
      title: '.*(fix|bug|correctly|use correct).*/i'
  - label: 'chore'
    sync: true
    matcher:
      title: '.*upgrade.*/i'
  - label: 'enhancement'
    sync: true
    matcher:
      title: '.*(improve|enhance|refine).*/i'
  - label: 'feature'
    sync: true
    matcher:
      title: '.*add support.*/i'
