FROM centos:7

# copy in the autograder
COPY . /autograder
# copy in the bootstrapping script
COPY bootstrap.sh /

# install sudo
# make the script executable
# create a directory that is only accessible to root
# create a new user called ag
RUN yum -y install sudo \
    && yum -y install make \
    && yum -y install epel-release \
    && yum -y install clang \
    && chmod +x /bootstrap.sh \
    && mkdir /autograder_results/ \
    && chown root:root /autograder_results \
    && chmod 700 /autograder_results \
    && useradd ag

# run the bootstrap script which should run the course grading script which will give us our results
CMD /bootstrap.sh
