import mustache from 'mustache';
import * as parse5 from 'parse5';

type DocumentFragment = parse5.DefaultTreeAdapterMap['documentFragment'];
type ChildNode = parse5.DefaultTreeAdapterMap['childNode'];

const PANEL_ELEMENTS = new Set(['pl-question-panel', 'pl-answer-panel', 'pl-submission-panel']);

// Note: all elements here are purely input-oriented. If a dual-purpose element is
// added (e.g. `pl-drawing`, which can be either input or display depending on its
// attributes), the nesting validation in `dfsCheckParseTree` may need to be made
// attribute-aware for that element rather than adding it here unconditionally.
const INPUT_ELEMENTS = new Set([
  'pl-multiple-choice',
  'pl-checkbox',
  'pl-integer-input',
  'pl-number-input',
  'pl-string-input',
  'pl-symbolic-input',
]);

export const SUPPORTED_ELEMENTS = new Set([...PANEL_ELEMENTS, ...INPUT_ELEMENTS]);

const BOOLEAN_TRUE_VALUES = ['true', 't', '1', 'True', 'T', 'TRUE', 'yes', 'y', 'Yes', 'Y', 'YES'];
const BOOLEAN_FALSE_VALUES = ['false', 'f', '0', 'False', 'F', 'FALSE', 'no', 'n', 'No', 'N', 'NO'];
const BOOLEAN_VALUES = [...BOOLEAN_TRUE_VALUES, ...BOOLEAN_FALSE_VALUES];

const mustacheTemplateRegex = /^\{\{.*\}\}$/;

type MustacheTextToken = ['text', string, number, number];
type MustacheNameToken = ['name', string, number, number];
type MustacheSectionToken = ['#' | '^' | '&', string, number, number, MustacheToken[]];
type MustacheToken = MustacheTextToken | MustacheNameToken | MustacheSectionToken;

export function extractMustacheTemplateNames(str: string): Set<string> {
  // We use a temporary writer to avoid any long-lived storage of the parsed
  // template in Mustache's cache.
  const writer = new mustache.Writer();
  const tokens = writer.parse(str);

  const names = new Set<string>();

  /** Helper function to recursively collect names. */
  function collectNames(tokensList: MustacheToken[]) {
    for (const token of tokensList) {
      const [type, value] = token;

      if (type === 'name' || type === '&') {
        // Handles {{variable}} and {{{variable}}} (unescaped)
        names.add(value);
      } else if (type === '#' || type === '^') {
        // Handles {{#section}}...{{/section}} and {{^inverted-section}}...{{/section}}
        // Record the section name itself.
        names.add(value);

        // Process any nested tokens.
        const children = token[4];
        if (Array.isArray(children)) {
          collectNames(children);
        }
      } else {
        // Other token types ('text', '!' for comments, '/' for closing tags) are implicitly ignored.
      }
    }
  }

  collectNames(tokens);

  // We deliberately ignore `.` (the current context). It's not a useful name
  // as it doesn't correspond to a variable in the template in isolation.
  names.delete('.');

  return names;
}

export function isValidMustacheTemplateName(name: string): boolean {
  // Mustache template names must be alphanumeric and can contain dots and underscores.
  return /^[a-zA-Z0-9_.]+$/.test(name);
}

interface ValidationResult {
  /** Array of errors that we'll instruct the LLM to fix. */
  errors: string[];
  /**
   * Contains a set of correct answers that must be generated by `server.py`.
   * These are expected to be set in `params["correct_answers"]`. Typically,
   * this corresponds to an `answers-name` attribute.
   *
   * Should be set even if there are other errors.
   */
  mandatoryPythonCorrectAnswers?: Set<string>;
}

interface HTMLValidationResult {
  /** Hard errors that must be fixed before saving. */
  errors: string[];
  /**
   * Warnings about likely issues. Unlike errors, warnings do not block
   * saving — they are included in the response so the LLM is informed,
   * but the question can still be saved. Callers may choose to promote
   * warnings to errors based on context (e.g. when creating a new question).
   */
  warnings: string[];
}

/**
 * Checks that the required attribute is an int (or mustache template) or adds an error to the provided list.
 * @param tag The name of the tag being checked.
 * @param key The attribute name.
 * @param val The attribute value.
 * @param errors The list of errors to add to.
 */
function assertInt(tag: string, key: string, val: string, errors: string[]) {
  if (!(/^-?\d+$/.test(val) || mustacheTemplateRegex.test(val))) {
    errors.push(
      `${tag}: value for attribute ${key} must be an integer, but value provided is "${val}"`,
    );
  }
}

/**
 * Checks that the required attribute is an float (or mustache template) or adds an error to the provided list.
 * @param tag The name of the tag being checked.
 * @param key The attribute name.
 * @param val The attribute value.
 * @param errors The list of errors to add to.
 */
function assertFloat(tag: string, key: string, val: string, errors: string[]) {
  if (!(/^-?(\d+\.?\d*|\.\d+)(e[+-]?\d+)?$/i.test(val) || mustacheTemplateRegex.test(val))) {
    errors.push(
      `${tag}: value for attribute ${key} must be an floating-point number, but value provided is "${val}"`,
    );
  }
}

/**
 * Checks that the required attribute is in a list of possibilities (or mustache template) or adds an error to the provided list.
 * @param tag The name of the tag being checked.
 * @param key The attribute name.
 * @param val The attribute value.
 * @param choices The list of potential choices for the attribute.
 * @param errors The list of errors to add to.
 */
function assertInChoices(
  tag: string,
  key: string,
  val: string,
  choices: string[],
  errors: string[],
) {
  if (!(choices.includes(val) || mustacheTemplateRegex.test(val))) {
    errors.push(
      `${tag}: value for attribute ${key} must be in ${choices.join(', ')}, but value provided is ${val}`,
    );
  }
}

/**
 * Checks that the required attribute is a boolean (or mustache template) or adds an error to the provided list.
 * @param tag The name of the tag being checked.
 * @param key The attribute name.
 * @param val The attribute value.
 * @param errors The list of errors to add to.
 */
function assertBool(tag: string, key: string, val: string, errors: string[]) {
  assertInChoices(tag, key, val, BOOLEAN_VALUES, errors);
}

/**
 * Checks if the given attribute value is a boolean `true` value.
 */
function isBooleanTrue(val: string): boolean {
  return BOOLEAN_TRUE_VALUES.includes(val.trim());
}

/**
 * Checks that a tag has valid attributes.
 * @param ast The tree to consider, rooted at the tag.
 * @returns The list of errors for the tag, if any.
 */
function checkTag(ast: DocumentFragment | ChildNode): ValidationResult {
  if ('tagName' in ast) {
    // The elements supported here should be kept in sync with those in
    // `context-parsers/documentation.ts`.
    switch (ast.tagName) {
      case 'pl-multiple-choice':
        return checkMultipleChoice(ast);
      case 'pl-integer-input':
        return checkIntegerInput(ast);
      case 'pl-number-input':
        return checkNumberInput(ast);
      case 'pl-string-input':
        return checkStringInput(ast);
      case 'pl-checkbox':
        return checkCheckbox(ast);
      case 'pl-symbolic-input':
        return checkSymbolicInput(ast);
      case 'pl-question-panel':
      case 'pl-answer-panel':
      case 'pl-submission-panel':
        return { errors: [] };
      case 'pl-answer':
        return { errors: [] }; // covered elsewhere
      default:
        if (ast.tagName.startsWith('pl-')) {
          const formattedSupportedElements = Array.from(SUPPORTED_ELEMENTS).join(', ');
          return {
            errors: [
              `${ast.tagName} is not a valid tag. You must use only the following tags: ${formattedSupportedElements}`,
            ],
          };
        }
    }
  }
  return { errors: [] };
}

/**
 * Checks that a `pl-multiple-choice` element has valid attributes.
 * @param ast The tree to consider, rooted at the tag.
 * @returns The list of errors for the tag, if any.
 */
function checkMultipleChoice(ast: DocumentFragment | ChildNode): ValidationResult {
  const errors: string[] = [];
  let usedAnswersName = false;
  let displayDropdown = false;
  let usedAllOfTheAbove = false;
  let usedNoneOfTheAbove = false;
  let usedAllOfTheAboveFeedback = false;
  let usedNoneOfTheAboveFeedback = false;
  let usedSize = false;
  const optionsOfTheAbove = ['false', 'random', 'correct', 'incorrect'];
  if ('attrs' in ast) {
    for (const attr of ast.attrs) {
      const key = attr.name;
      const val = attr.value;
      switch (key) {
        case 'answers-name':
          usedAnswersName = true;
          break;
        case 'weight':
          assertInt('pl-multiple-choice', key, val, errors);
          break;
        case 'display':
          assertInChoices('pl-multiple-choice', key, val, ['block', 'inline', 'dropdown'], errors);
          if (val === 'dropdown') {
            displayDropdown = true;
          }
          break;
        case 'number-answers':
          assertInt('pl-multiple-choice', key, val, errors);
          break;
        case 'order':
          assertInChoices(
            'pl-multiple-choice',
            key,
            val,
            ['random', 'ascend', 'descend', 'fixed'],
            errors,
          );
          break;
        case 'hide-letter-keys':
        case 'hide-score-badge':
        case 'fixed-order':
        case 'inline':
          assertBool('pl-multiple-choice', key, val, errors);
          break;
        case 'placeholder':
        case 'aria-label':
        case 'external-json':
        case 'external-json-correct-key':
        case 'external-json-incorrect-key':
          break;
        case 'all-of-the-above':
          assertInChoices('pl-multiple-choice', key, val, optionsOfTheAbove, errors);
          if (optionsOfTheAbove.includes(val) && val !== 'false') {
            usedAllOfTheAbove = true;
          }
          break;
        case 'none-of-the-above':
          assertInChoices('pl-multiple-choice', key, val, optionsOfTheAbove, errors);
          if (optionsOfTheAbove.includes(val) && val !== 'false') {
            usedNoneOfTheAbove = true;
          }
          break;
        case 'all-of-the-above-feedback':
          usedAllOfTheAboveFeedback = true;
          break;
        case 'none-of-the-above-feedback':
          usedNoneOfTheAboveFeedback = true;
          break;
        case 'allow-blank':
          assertBool('pl-multiple-choice', key, val, errors);
          break;
        case 'size':
          usedSize = true;
          assertInt('pl-multiple-choice', key, val, errors);
          break;
        default:
          errors.push(`pl-multiple-choice: ${key} is not a valid attribute.`);
      }
    }
  }
  if (!usedAnswersName) {
    errors.push('pl-multiple-choice: answers-name is a required attribute.');
  }
  if (!usedAllOfTheAbove && usedAllOfTheAboveFeedback) {
    errors.push(
      'pl-multiple-choice: if using all-of-the-above-feedback, you must also use all-of-the-above.',
    );
  }
  if (!usedNoneOfTheAbove && usedNoneOfTheAboveFeedback) {
    errors.push(
      'pl-multiple-choice: if using none-of-the-above-feedback, you must also use none-of-the-above.',
    );
  }
  if (!displayDropdown && usedSize) {
    errors.push('pl-multiple-choice: if using size, you must also use set display to "dropdown".');
  }

  let errorsChildren: string[] = [];
  if ('childNodes' in ast) {
    for (const child of ast.childNodes) {
      if ('tagName' in child && child.tagName) {
        if (child.tagName === 'pl-answer') {
          errorsChildren = errorsChildren.concat(checkAnswerMultipleChoice(child));
        } else {
          errorsChildren.push(`pl-multiple-choice: ${child.tagName} is not a valid child tag.`);
        }
      }
    }
  }

  return { errors: errors.concat(errorsChildren) };
}

/**
 * Checks that a `pl-integer-input` element has valid attributes.
 * @param ast The tree to consider, rooted at the tag to consider.
 * @returns The list of errors for the tag, if any.
 */
function checkIntegerInput(ast: DocumentFragment | ChildNode): ValidationResult {
  const errors: string[] = [];
  let answersName: string | null = null;
  let allowBlank = false;
  let usedBlankValue = false;
  let usedCorrectAnswer = false;

  if ('attrs' in ast) {
    for (const attr of ast.attrs) {
      const key = attr.name;
      const val = attr.value;
      switch (key) {
        case 'answers-name':
          answersName = val;
          break;
        case 'weight':
        case 'size':
          assertInt('pl-integer-input', key, val, errors);
          break;
        case 'correct-answer':
          assertInt('pl-integer-input', key, val, errors);
          usedCorrectAnswer = true;
          if (mustacheTemplateRegex.test(val)) {
            errors.push(
              "pl-integer-input: correct-answer attribute value must not be a Mustache template. If the correct answer depends on dynamic parameters, set `data['correct_answers']` accordingly in `server.py` and remove this attribute.",
            );
          }
          break;
        case 'label':
        case 'aria-label':
        case 'suffix':
        case 'placeholder':
          break;
        case 'show-help-text':
        case 'show-score':
          assertBool('pl-integer-input', key, val, errors);
          break;
        case 'allow-blank':
          assertBool('pl-integer-input', key, val, errors);
          allowBlank = isBooleanTrue(val);
          break;
        case 'base':
          // TODO: validate that correct-answer is the right base
          assertInt('pl-integer-input', key, val, errors);
          break;
        case 'display':
          assertInChoices('pl-integer-input', key, val, ['block', 'inline'], errors);
          break;
        case 'blank-value':
          usedBlankValue = true;
          break;
        default:
          errors.push(`pl-integer-input: ${key} is not a valid attribute.`);
      }
    }
  }
  if (!answersName) {
    errors.push('pl-integer-input: answers-name is a required attribute.');
  }
  if (usedBlankValue && !allowBlank) {
    errors.push('pl-integer-input: you must set allow-blank to true to use blank-value.');
  }
  return {
    errors,
    // If a correct answer was not specified with the `correct-answer` attribute,
    // then the `answers-name` attribute must be generated in Python.
    mandatoryPythonCorrectAnswers:
      !usedCorrectAnswer && answersName ? new Set([answersName]) : undefined,
  };
}

/**
 * Checks that a `pl-symbolic-input` element has valid attributes.
 * @param ast The tree to consider, rooted at the tag to consider.
 * @returns The list of errors for the tag, if any.
 */
function checkSymbolicInput(ast: DocumentFragment | ChildNode): ValidationResult {
  const errors: string[] = [];
  let answersName: string | null = null;
  let allowBlank = false;
  let usedBlankValue = false;
  let usedCorrectAnswer = false;

  if ('attrs' in ast) {
    for (const attr of ast.attrs) {
      const key = attr.name;
      const val = attr.value;
      switch (key) {
        case 'answers-name':
          answersName = val;
          break;
        case 'weight':
        case 'size':
          assertInt('pl-symbolic-input', key, val, errors);
          break;
        case 'correct-answer':
          usedCorrectAnswer = true;
          if (mustacheTemplateRegex.test(val)) {
            errors.push(
              "pl-symbolic-input: correct-answer attribute value must not be a Mustache template. If the correct answer depends on dynamic parameters, set `data['correct_answers']` accordingly in `server.py` and remove this attribute.",
            );
          }
          break;
        case 'label':
        case 'aria-label':
        case 'variables':
        case 'placeholder':
        case 'custom-functions':
        case 'suffix':
        case 'additional-simplifications':
          break;
        case 'display':
          assertInChoices('pl-symbolic-input', key, val, ['block', 'inline'], errors);
          break;
        case 'imaginary-unit-for-display':
          assertInChoices('pl-symbolic-input', key, val, ['i', 'j'], errors);
          break;
        case 'allow-complex':
        case 'allow-trig-functions':
        case 'show-help-text':
        case 'show-score':
        case 'formula-editor':
        case 'display-log-as-ln':
        case 'display-simplified-expression':
          assertBool('pl-symbolic-input', key, val, errors);
          break;
        case 'allow-blank':
          assertBool('pl-symbolic-input', key, val, errors);
          allowBlank = isBooleanTrue(val);
          break;
        case 'blank-value':
          usedBlankValue = true;
          break;
        default:
          errors.push(`pl-symbolic-input: ${key} is not a valid attribute.`);
      }
    }
  }
  if (!answersName) {
    errors.push('pl-symbolic-input: answers-name is a required attribute.');
  }
  if (usedBlankValue && !allowBlank) {
    errors.push('pl-symbolic-input: must set `allow-blank` to true if setting `blank-value`');
  }
  return {
    errors,
    // If a correct answer was not specified with the `correct-answer` attribute,
    // then the `answers-name` attribute must be generated in Python.
    mandatoryPythonCorrectAnswers:
      !usedCorrectAnswer && answersName ? new Set([answersName]) : undefined,
  };
}

/**
 * Checks that a `pl-number-input` element has valid attributes.
 * @param ast The tree to consider, rooted at the tag to consider.
 * @returns The list of errors for the tag, if any.
 */
function checkNumberInput(ast: DocumentFragment | ChildNode): ValidationResult {
  const errors: string[] = [];
  let answersName: string | null = null;
  let usedRelabs = true;
  let usedRtol = false;
  let usedAtol = false;
  let usedDigits = false;
  let allowBlank = false;
  let usedBlankValue = false;
  let usedCorrectAnswer = false;

  if ('attrs' in ast) {
    for (const attr of ast.attrs) {
      const key = attr.name;
      const val = attr.value;
      switch (key) {
        case 'answers-name':
          answersName = val;
          break;
        case 'weight':
        case 'size':
          assertInt('pl-number-input', key, val, errors);
          break;
        case 'correct-answer':
          assertFloat('pl-number-input', key, val, errors);
          usedCorrectAnswer = true;
          if (mustacheTemplateRegex.test(val)) {
            errors.push(
              "pl-number-input: correct-answer attribute value must not be a Mustache template. If the correct answer depends on dynamic parameters, set `data['correct_answers']` accordingly in `server.py` and remove this attribute.",
            );
          }
          break;
        case 'label':
        case 'aria-label':
        case 'suffix':
        case 'placeholder':
        case 'custom-format':
          break;
        case 'display':
          assertInChoices('pl-number-input', key, val, ['block', 'inline'], errors);
          break;
        case 'comparison':
          assertInChoices('pl-number-input', key, val, ['relabs', 'sigfig', 'decdig'], errors);
          if (val !== 'relabs') {
            usedRelabs = false;
          }
          break;
        case 'rtol':
          assertFloat('pl-number-input', key, val, errors);
          usedRtol = true;
          break;
        case 'atol':
          assertFloat('pl-number-input', key, val, errors);
          usedAtol = true;
          break;
        case 'digits':
          assertInt('pl-number-input', key, val, errors);
          usedDigits = true;
          break;
        case 'allow-complex':
        case 'show-correct-answer':
        case 'show-placeholder':
        case 'allow-fractions':
        case 'show-help-text':
        case 'show-score':
          assertBool('pl-number-input', key, val, errors);
          break;
        case 'allow-blank':
          assertBool('pl-number-input', key, val, errors);
          allowBlank = isBooleanTrue(val);
          break;
        case 'blank-value':
          usedBlankValue = true;
          break;
        default:
          errors.push(`pl-number-input: ${key} is not a valid attribute.`);
      }
    }
  }
  if (!answersName) {
    errors.push('pl-number-input: answers-name is a required attribute.');
  }
  if ((usedRtol || usedAtol) && !usedRelabs) {
    errors.push(
      'pl-number-input: comparison modes decdigs and sigfigs use digits, not rtol or atol.',
    );
  }
  if (usedDigits && usedRelabs) {
    errors.push('pl-number-input: comparison mode relabs uses rtol and atol, not digits.');
  }
  if (usedBlankValue && !allowBlank) {
    errors.push('pl-number-input: you must set allow-blank to true to use blank-value.');
  }
  return {
    errors,
    // If a correct answer was not specified with the `correct-answer` attribute,
    // then the `answers-name` attribute must be generated in Python.
    mandatoryPythonCorrectAnswers:
      !usedCorrectAnswer && answersName ? new Set([answersName]) : undefined,
  };
}

/**
 * Checks that a `pl-answer` element in a multiple choice tag has valid attributes.
 * @param ast The tree to consider, rooted at the tag to consider.
 * @returns The list of errors for the tag, if any.
 */
function checkAnswerMultipleChoice(ast: DocumentFragment | ChildNode): string[] {
  const errors: string[] = [];
  if ('attrs' in ast) {
    for (const attr of ast.attrs) {
      switch (attr.name) {
        case 'correct':
          assertBool('pl-answer (for pl-multiple-choice)', attr.name, attr.value, errors);
          break;
        case 'feedback':
          break;
        case 'score':
          assertFloat('pl-answer (for pl-multiple-choice)', attr.name, attr.value, errors);
          break;
        default:
          errors.push(`pl-answer (for pl-multiple-choice): ${attr.name} is not a valid attribute.`);
      }
    }
  }
  return errors;
}

/**
 * Checks that a `pl-answer` element in a multiple choice tag has valid attributes.
 * @param ast The tree to consider, rooted at the tag to consider.
 * @returns The list of errors for the tag, if any.
 */
function checkAnswerCheckbox(ast: DocumentFragment | ChildNode): string[] {
  const errors: string[] = [];
  if ('attrs' in ast) {
    for (const attr of ast.attrs) {
      switch (attr.name) {
        case 'correct':
          assertBool('pl-answer (for pl-checkbox)', attr.name, attr.value, errors);
          break;
        case 'feedback':
          break;
        default:
          errors.push(`pl-answer (for pl-checkbox): ${attr.name} is not a valid attribute.`);
      }
    }
  }
  return errors;
}

/**
 * Checks that a `pl-string-input` element has valid attributes.
 * @param ast The tree to consider, rooted at the tag to consider.
 * @returns The list of errors for the tag, if any.
 */
function checkStringInput(ast: DocumentFragment | ChildNode): ValidationResult {
  const errors: string[] = [];
  let answersName: string | null = null;
  let usedCorrectAnswer = false;
  if ('attrs' in ast) {
    for (const attr of ast.attrs) {
      const key = attr.name;
      const val = attr.value;
      switch (key) {
        case 'answers-name':
          answersName = val;
          break;
        case 'weight':
        case 'size':
          assertInt('pl-string-input', key, val, errors);
          break;
        case 'correct-answer':
          usedCorrectAnswer = true;
          break;
        case 'label':
        case 'aria-label':
        case 'suffix':
        case 'placeholder':
        case 'initial-value':
        case 'blank-value':
          break;
        case 'display':
          assertInChoices('pl-string-input', key, val, ['block', 'inline'], errors);
          break;
        case 'remove-leading-trailing':
        case 'remove-spaces':
        case 'allow-blank':
        case 'ignore-case':
        case 'normalize-to-ascii':
        case 'show-help-text':
        case 'show-score':
        case 'multiline':
        case 'escape-unicode':
          assertBool('pl-string-input', key, val, errors);
          break;
        default:
          errors.push(`pl-string-input: ${attr.name} is not a valid attribute.`);
      }
    }
  }
  if (!answersName) {
    errors.push('pl-string-input: answers-name is a required attribute.');
  }
  return {
    errors,
    // If a correct answer was not specified with the `correct-answer` attribute,
    // then the `answers-name` attribute must be generated in Python.
    mandatoryPythonCorrectAnswers:
      !usedCorrectAnswer && answersName ? new Set([answersName]) : undefined,
  };
}

/**
 * Checks that a `pl-checkbox` element has valid attributes.
 * @param ast The tree to consider, rooted at the tag to consider.
 * @returns The list of errors for the tag, if any.
 */
function checkCheckbox(ast: DocumentFragment | ChildNode): ValidationResult {
  const errors: string[] = [];
  let usedAnswersName = false;
  let usedPartialCreditBoolean = false;
  let usedPartialCreditEnum = false;
  let usedPartialCreditMethod = false;
  const partialCreditEnumValues = ['off', 'coverage', 'each-answer', 'net-correct'];
  if ('attrs' in ast) {
    for (const attr of ast.attrs) {
      const key = attr.name;
      const val = attr.value;
      switch (key) {
        case 'answers-name':
          usedAnswersName = true;
          break;
        case 'weight':
        case 'number-answers':
        case 'min-correct':
        case 'max-correct':
        case 'min-select':
        case 'max-select':
          assertInt('pl-checkbox', key, val, errors);
          break;
        case 'display':
          assertInChoices('pl-checkbox', key, val, ['block', 'inline'], errors);
          break;
        case 'order':
          assertInChoices('pl-checkbox', key, val, ['random', 'fixed'], errors);
          break;
        case 'inline':
        case 'fixed-order':
        case 'hide-help-text':
        case 'detailed-help-text':
        case 'hide-answer-panel':
        case 'hide-score-badge':
        case 'hide-letter-keys':
        case 'show-number-correct':
          assertBool('pl-checkbox', key, val, errors);
          break;

        case 'partial-credit':
          // Accepts both old style (boolean) and new style (enum)
          assertInChoices(
            'pl-checkbox',
            key,
            val,
            [...BOOLEAN_VALUES, ...partialCreditEnumValues],
            errors,
          );
          if (BOOLEAN_VALUES.includes(val)) {
            usedPartialCreditBoolean = true;
          } else if (partialCreditEnumValues.includes(val)) {
            usedPartialCreditEnum = true;
          }
          break;
        case 'partial-credit-method':
          // Deprecated: used with old-style boolean partial-credit
          assertInChoices('pl-checkbox', key, val, ['COV', 'EDC', 'PC'], errors);
          usedPartialCreditMethod = true;
          break;
        default:
          errors.push(`pl-checkbox: ${key} is not a valid attribute.`);
      }
    }
  }
  if (!usedAnswersName) {
    errors.push('pl-checkbox: answers-name is a required attribute.');
  }
  if (usedPartialCreditMethod && !usedPartialCreditBoolean) {
    errors.push(
      'pl-checkbox: partial-credit-method can only be used with boolean partial-credit values (true/false). Use partial-credit="off|coverage|each-answer|net-correct" instead.',
    );
  }
  if (usedPartialCreditEnum && usedPartialCreditMethod) {
    errors.push(
      'pl-checkbox: partial-credit-method cannot be used with new-style partial-credit values. Remove partial-credit-method.',
    );
  }

  let errorsChildren: string[] = [];
  if ('childNodes' in ast) {
    for (const child of ast.childNodes) {
      if ('tagName' in child && child.tagName) {
        if (child.tagName === 'pl-answer') {
          errorsChildren = errorsChildren.concat(checkAnswerCheckbox(child));
        } else {
          errorsChildren.push(`pl-checkbox: ${child.tagName} is not a valid child tag.`);
        }
      }
    }
  }

  return { errors: errors.concat(errorsChildren) };
}

interface DfsResult extends ValidationResult {
  warnings: string[];
  mandatoryPythonCorrectAnswers: Set<string>;
}

/**
 * Checks the entire parse tree for errors in common PL tags recursively.
 * @param ast The tree to consider.
 * @param enclosingPanel The name of the enclosing panel element (e.g. 'pl-submission-panel'), if any.
 * @returns Errors, warnings, and mandatory correct answers.
 */
function dfsCheckParseTree(ast: DocumentFragment | ChildNode, enclosingPanel?: string): DfsResult {
  let { errors, mandatoryPythonCorrectAnswers = new Set<string>() } = checkTag(ast);
  let warnings: string[] = [];

  if ('tagName' in ast && INPUT_ELEMENTS.has(ast.tagName) && enclosingPanel) {
    warnings.push(
      `<${ast.tagName}> must not be placed inside <${enclosingPanel}>. ` +
        'Input elements must be placed at the top level of question.html (outside any panel element) ' +
        'so they render correctly in the question, submission, and answer panels. ' +
        `Move <${ast.tagName}> outside of <${enclosingPanel}>.`,
    );
  }

  const childPanel =
    'tagName' in ast && PANEL_ELEMENTS.has(ast.tagName) ? ast.tagName : enclosingPanel;

  if ('childNodes' in ast) {
    for (const child of ast.childNodes) {
      const childResult = dfsCheckParseTree(child, childPanel);
      errors = errors.concat(childResult.errors);
      warnings = warnings.concat(childResult.warnings);
      childResult.mandatoryPythonCorrectAnswers.forEach((x) =>
        mandatoryPythonCorrectAnswers.add(x),
      );
    }
  }

  return { errors, warnings, mandatoryPythonCorrectAnswers };
}

/**
 * Checks for errors and warnings in common PL elements in a question.html file.
 * @param file The raw text of the file to use.
 * @param hasServerPy True if a server.py file is present, else false.
 * @returns Errors that must be fixed and warnings about likely issues.
 */
export function validateHTML(file: string, hasServerPy: boolean): HTMLValidationResult {
  const forbiddenTagMatch = file.match(/^\s*<(!doctype|html|body|head)[\s>]/i);
  if (forbiddenTagMatch) {
    const tag = forbiddenTagMatch[1].toLowerCase();
    if (tag === '!doctype') {
      return {
        errors: [
          'The <!DOCTYPE> declaration must not be included. Only generate the inner content that would go inside the <body> tag.',
        ],
        warnings: [],
      };
    }
    return {
      errors: [
        `The <${tag}> tag must not be included. Only generate the inner content that would go inside the <body> tag.`,
      ],
      warnings: [],
    };
  }

  const tree = parse5.parseFragment(file);
  const { errors, warnings, mandatoryPythonCorrectAnswers } = dfsCheckParseTree(tree);

  const usedTemplateNames = extractMustacheTemplateNames(file);
  const templates = [
    ...usedTemplateNames,
    ...Array.from(mandatoryPythonCorrectAnswers).map((x) => `correct_answers.${x}`),
  ];

  if (!hasServerPy && templates.length > 0) {
    errors.push(`Create a server.py file to generate the following: ${templates.join(', ')}`);
  }

  for (const template of usedTemplateNames) {
    if (!isValidMustacheTemplateName(template)) {
      errors.push(
        `Template of ${template} must be in mustache format. Please adjust so that any logic done in the template is instead done in server.py`,
      );
    }
  }

  return { errors, warnings };
}
