# yaml-language-server: $schema=https://storage.googleapis.com/coderabbit_public_assets/schema.v2.json
language: en
reviews:
  profile: chill
  request_changes_workflow: false # Do not approve after comments resolved
  high_level_summary: false
  review_status: false # Do not make comments on PRs that are not ready for review
  collapse_walkthrough: true
  changed_files_summary: true
  sequence_diagrams: false
  related_issues: false
  related_prs: false
  suggested_labels: true
  auto_apply_labels: false
  suggested_reviewers: true
  poem: false
  labeling_instructions: []
  path_filters: []
  path_instructions: []
  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: []
    drafts: false
    base_branches:
      - master
  pre_merge_checks:
    docstrings:
      mode: 'off'
  finishing_touches:
    docstrings:
      enabled: true
  tools:
    # Our ESLint config relies on a package that exists in this repository but
    # must be built and linked first, which it doesn't know how to do. To
    # prevent spurious warnings, we just disable ESLint for now.
    eslint:
      enabled: false
    # The version of ruff (0.8.2) used by coderabbit is not modern enough to support our config.
    ruff:
      enabled: false
    # Biome is flagging issues in our test suite that aren't relevant (lint/suspicious/noDuplicateTestHooks)
    biome:
      enabled: false

chat:
  auto_reply: true

knowledge_base:
  learnings:
    scope: local # Repository-specific learnings
  issues:
    scope: local # Repository-specific issues
  pull_requests:
    scope: local # Repository-specific pull requests
