# yaml-language-server: $schema=https://raw.githubusercontent.com/hadolint/hadolint/master/contrib/hadolint.json
ignored:
  - DL3007 # latest tag is not recommended
  - DL3008 # pin versions in apt get install
  # Will be resolved in a future PR
  - DL3003
  - SC3009
  - DL3004
  - DL3009
  - DL3015
  - DL3059
  - SC2238
  - DL3025
  - DL3027
  - SC2086
  - DL4006
  - DL3042
  - SC2046
  - SC2086
  - DL3060
