# Line length
MD013: false
# Multiple headings with the same content
MD024: false
# These rules should be enabled/disabled eventually
MD033: false
MD034: false
MD038: false
MD036: false
MD041: false
MD045: false
MD046: false
MD053: false
