version: 2

build:
  os: ubuntu-22.04
  tools:
    python: '3.10'
  jobs:
    pre_build:
      - curl -fsSL https://d2lang.com/install.sh | sh -s --
      - cp $HOME/.local/bin/d2 $READTHEDOCS_OUTPUT/bin/d2

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: docs/requirements.txt
