# yaml-language-server: $schema=https://raw.githubusercontent.com/readthedocs/readthedocs.org/master/readthedocs/rtd_tests/fixtures/spec/v2/schema.json
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: '3.13'
  jobs:
    pre_create_environment:
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
    create_environment:
      - uv venv $READTHEDOCS_VIRTUALENV_PATH
    install:
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync --frozen --group docs
    pre_build:
      - D2_VERSION=$(curl -fsSLI -o /dev/null -w '%{url_effective}' https://github.com/terrastruct/d2/releases/latest | sed 's|.*/||') && curl -fsSL https://github.com/terrastruct/d2/releases/download/$D2_VERSION/d2-$D2_VERSION-linux-amd64.tar.gz | tar -xz --strip-components=2 -C $READTHEDOCS_VIRTUALENV_PATH/bin d2-$D2_VERSION/bin/d2

mkdocs:
  configuration: mkdocs.yml
