# yaml-language-server: $schema=https://raw.githubusercontent.com/readthedocs/readthedocs.org/master/readthedocs/rtd_tests/fixtures/spec/v2/schema.json
version: 2

build:
  os: ubuntu-24.04
  tools:
    python: '3.13'
  jobs:
    pre_build:
      - curl -fsSL https://d2lang.com/install.sh | sh -s --
      - cp $HOME/.local/bin/d2 $READTHEDOCS_VIRTUALENV_PATH/bin/d2
    install:
      - pip install -U pip
      - pip install --group docs

mkdocs:
  configuration: mkdocs.yml
