version: 2

build:
  os: ubuntu-22.04
  tools:
    python: '3.10'
  commands:
    - curl -fsSL https://d2lang.com/install.sh | sh -s -- # Install D2
    - python -m pip install --upgrade --no-cache-dir pip setuptools
    - python -m pip install --upgrade --no-cache-dir mkdocs
    - python -m pip install --exists-action=w --no-cache-dir -r docs/requirements.txt
    - cat mkdocs.yml

mkdocs:
  configuration: mkdocs.yml

python:
  install:
    - requirements: docs/requirements.txt
