# yaml-language-server: $schema=https://yarnpkg.com/configuration/yarnrc.json
enableGlobalCache: true

# We rely on a node_modules based setup for serving assets (e.g. nodeModulesScripts).
nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.3.0.cjs
