import type { Config } from '@reteps/tree-sitter-htmlmustache/browser';

// This should be kept in sync with `.htmlmustache.jsonc`
export const htmlMustacheConfig: Config = {
  printWidth: 100,
  noBreakDelimiters: [
    { start: '$', end: '$' },
    { start: '$$', end: '$$' },
    { start: '\\(', end: '\\)' },
    { start: '\\[', end: '\\]' },
  ],
  rules: {
    preferMustacheComments: 'warning',
    unrecognizedHtmlTags: 'warning',
  },
  customTags: [
    {
      name: 'pl-code',
      display: 'block',
      languageAttribute: 'language',
      indent: 'attribute',
      indentAttribute: 'normalize-whitespace',
    },
    {
      name: 'pl-file-editor',
      display: 'block',
      languageAttribute: 'ace-mode',
      languageMap: {
        'ace/mode/python': 'python',
        'ace/mode/c_cpp': 'c',
        'ace/mode/java': 'java',
        'ace/mode/html': 'html',
        'ace/mode/markdown': 'markdown',
        'ace/mode/r': 'r',
        'ace/mode/dot': 'dot',
        'ace/mode/javascript': 'javascript',
        'ace/mode/typescript': 'typescript',
        'ace/mode/sql': 'sql',
        'ace/mode/json': 'json',
        'ace/mode/xml': 'xml',
        'ace/mode/yaml': 'yaml',
        'ace/mode/css': 'css',
        'ace/mode/sh': 'bash',
      },
    },
    {
      name: 'pl-rich-text-editor',
      display: 'block',
      languageAttribute: 'format',
    },
    { name: 'markdown', display: 'block', languageDefault: 'markdown' },
    { name: 'pl-graph', display: 'block', languageDefault: 'dot' },
    { name: 'pl-question-panel', display: 'block' },
    { name: 'pl-submission-panel', display: 'block' },
    { name: 'pl-answer-panel', display: 'block' },
    // Submission
    { name: 'pl-big-o-input' },
    { name: 'pl-excalidraw' },
    { name: 'pl-file-upload' },
    { name: 'pl-image-capture' },
    { name: 'pl-integer-input' },
    { name: 'pl-matching' },
    { name: 'pl-statement' },
    { name: 'pl-option' },
    { name: 'pl-matrix-component-input' },
    { name: 'pl-matrix-input' },
    { name: 'pl-checkbox' },
    { name: 'pl-multiple-choice' },
    { name: 'pl-order-blocks' },
    { name: 'pl-block-group' },
    { name: 'pl-answer' },
    { name: 'pl-number-input' },
    { name: 'pl-string-input' },
    { name: 'pl-symbolic-input' },
    { name: 'pl-units-input' },
    // Decorative
    { name: 'pl-card' },
    { name: 'pl-dataframe' },
    { name: 'pl-external-grader-variables' },
    { name: 'pl-figure' },
    { name: 'pl-file-download' },
    { name: 'pl-file-preview' },
    { name: 'pl-matrix-latex' },
    { name: 'pl-python-variable' },
    { name: 'pl-template' },
    { name: 'pl-variable-output' },
    { name: 'pl-variable' },
    { name: 'pl-xss-safe' },
    { name: 'pl-overlay' },
    { name: 'pl-background' },
    { name: 'pl-location' },
    // Conditional elements
    { name: 'pl-external-grader-results' },
    { name: 'pl-hidden-hints' },
    { name: 'pl-hint' },
    { name: 'pl-hide-in-manual-grading' },
    { name: 'pl-manual-grading-only' },
    { name: 'pl-hide-in-answer-panel' },
    { name: 'pl-workspace' },
    { name: 'pl-hide-in-panel' },
    // Deprecated elements
    { name: 'pl-dropdown' },
    { name: 'pl-prairiedraw-figure' },
    { name: 'pl-variable-score' },
    { name: 'pl-github-link' },
    // pl-drawing
    { name: 'pl-drawing' },
    { name: 'pl-drawing-answer' },
    { name: 'pl-drawing-button' },
    { name: 'pl-drawing-group' },
    { name: 'pl-drawing-initial' },
    { name: 'pl-controls' },
    { name: 'pl-controls-group' },
    { name: 'pl-3pointrod' },
    { name: 'pl-4pointrod' },
    { name: 'pl-arc' },
    { name: 'pl-arc-dimensions' },
    { name: 'pl-arc-vector' },
    { name: 'pl-axes' },
    { name: 'pl-battery' },
    { name: 'pl-capacitor' },
    { name: 'pl-circle' },
    { name: 'pl-clamped' },
    { name: 'pl-coil' },
    { name: 'pl-collar-rod' },
    { name: 'pl-controlled-curved-line' },
    { name: 'pl-controlled-line' },
    { name: 'pl-coordinates' },
    { name: 'pl-dimensions' },
    { name: 'pl-distributed-load' },
    { name: 'pl-double-headed-vector' },
    { name: 'pl-fixed-pin' },
    { name: 'pl-graph-line' },
    { name: 'pl-inductor' },
    { name: 'pl-line' },
    { name: 'pl-paired-vector' },
    { name: 'pl-point' },
    { name: 'pl-polygon' },
    { name: 'pl-pulley' },
    { name: 'pl-rectangle' },
    { name: 'pl-resistor' },
    { name: 'pl-rod' },
    { name: 'pl-roller' },
    { name: 'pl-spring' },
    { name: 'pl-switch' },
    { name: 'pl-text' },
    { name: 'pl-triangle' },
    { name: 'pl-vector' },
    // pl-sketch
    { name: 'pl-sketch' },
    { name: 'pl-sketch-grade' },
    { name: 'pl-sketch-initial' },
    { name: 'pl-sketch-solution' },
    { name: 'pl-sketch-tool' },
    // Non-PL custom elements
    { name: 'clickable-image' },
    { name: 'course-element' },
    { name: 'extendable-element' },
    { name: 'math-field' },
  ],
};
