const compat = require('@prairielearn/preact-cjs/compat');
const { useErrorBoundary } = require('@prairielearn/preact-cjs/hooks');

module.exports = {
  Children: compat.Children,
  Component: compat.Component,
  Fragment: compat.Fragment,
  PureComponent: compat.PureComponent,
  StrictMode: compat.StrictMode,
  Suspense: compat.Suspense,
  SuspenseList: compat.SuspenseList,
  cloneElement: compat.cloneElement,
  createContext: compat.createContext,
  createElement: compat.createElement,
  createFactory: compat.createFactory,
  createPortal: compat.createPortal,
  createRef: compat.createRef,
  findDOMNode: compat.findDOMNode,
  flushSync: compat.flushSync,
  forwardRef: compat.forwardRef,
  hydrate: compat.hydrate,
  isElement: compat.isValidElement,
  isFragment: compat.isFragment,
  isMemo: compat.isMemo,
  isValidElement: compat.isValidElement,
  lazy: compat.lazy,
  memo: compat.memo,
  render: compat.render,
  startTransition: compat.startTransition,
  unmountComponentAtNode: compat.unmountComponentAtNode,
  unstable_batchedUpdates: compat.unstable_batchedUpdates,
  useCallback: compat.useCallback,
  useContext: compat.useContext,
  useDebugValue: compat.useDebugValue,
  useDeferredValue: compat.useDeferredValue,
  useEffect: compat.useEffect,
  useErrorBoundary,
  useId: compat.useId,
  useImperativeHandle: compat.useImperativeHandle,
  useLayoutEffect: compat.useLayoutEffect,
  useInsertionEffect: compat.useInsertionEffect,
  useMemo: compat.useMemo,
  useReducer: compat.useReducer,
  useRef: compat.useRef,
  useState: compat.useState,
  useSyncExternalStore: compat.useSyncExternalStore,
  useTransition: compat.useTransition,
  version: compat.version,
};
