CREATE TABLE IF NOT EXISTS jobs (
    id SERIAL PRIMARY KEY,
    start_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    finish_date TIMESTAMP WITH TIME ZONE,
    course_id INTEGER REFERENCES courses ON DELETE CASCADE ON UPDATE CASCADE,
    number INTEGER,
    job_sequence_id INTEGER REFERENCES job_sequences ON DELETE CASCADE ON UPDATE CASCADE,
    number_in_sequence INTEGER,
    last_in_sequence BOOLEAN,
    user_id INTEGER REFERENCES users ON DELETE CASCADE ON UPDATE CASCADE,
    authn_user_id INTEGER REFERENCES users ON DELETE CASCADE ON UPDATE CASCADE,
    type TEXT,
    description TEXT,
    status enum_job_status,
    stdin TEXT,
    stdout TEXT,
    stderr TEXT,
    output TEXT,
    command TEXT,
    arguments TEXT[],
    working_directory TEXT,
    exit_code INTEGER,
    exit_signal TEXT,
    error_message TEXT,
    UNIQUE (course_id, number),
    UNIQUE (job_sequence_id, number_in_sequence)
);
