/* From PS exams as of 2018-02-24 */

ALTER TABLE exams ADD COLUMN IF NOT EXISTS exam_string text NOT NULL;
ALTER TABLE exams ADD COLUMN IF NOT EXISTS first_date date NOT NULL;
ALTER TABLE exams ADD COLUMN IF NOT EXISTS late_date date NOT NULL;
ALTER TABLE exams ADD COLUMN IF NOT EXISTS final_date date NULL;
ALTER TABLE exams ADD COLUMN IF NOT EXISTS exam_length smallint NOT NULL;
ALTER TABLE exams ADD COLUMN IF NOT EXISTS proctor_info text NULL;
ALTER TABLE exams ADD COLUMN IF NOT EXISTS avail_date timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE exams ADD COLUMN IF NOT EXISTS optional smallint NOT NULL DEFAULT 0;
ALTER TABLE exams ADD COLUMN IF NOT EXISTS semester_final smallint NOT NULL DEFAULT 0;
