ALTER TABLE instance_questions ADD COLUMN IF NOT EXISTS manual_score DOUBLE PRECISION DEFAULT NULL;
ALTER TABLE instance_questions ADD COLUMN IF NOT EXISTS autograde_score DOUBLE PRECISION DEFAULT NULL;
