ALTER TABLE ADD COLUMN IF NOT EXISTS uid_attribute TEXT NOT NULL;
ALTER TABLE ADD COLUMN IF NOT EXISTS uin_attribute TEXT NOT NULL;
ALTER TABLE ADD COLUMN IF NOT EXISTS name_atttribute TEXT NOT NULL;
