
module.exports.sql
    = "CREATE OR REPLACE FUNCTION format_interval_short(d interval) RETURNS text AS $$\n"
    + "DECLARE\n"
    + "    days integer;\n"
    + "    hours integer;\n"
    + "    mins integer;\n"
    + "    s varchar;\n"
    + "BEGIN\n"
    + "    days := div(CAST(floor(EXTRACT(EPOCH FROM d)) AS integer), 60 * 60 * 24);\n"
    + "    hours := mod(div(CAST(floor(EXTRACT(EPOCH FROM d)) AS integer), 60 * 60), 24);\n"
    + "    mins := mod(div(CAST(floor(EXTRACT(EPOCH FROM d)) AS integer), 60), 60);\n"
    + "    s := '';\n"
    + "    IF days > 0 THEN\n"
    + "        s := s || days::text || 'd';\n"
    + "    END IF;\n"
    + "    IF hours > 0 THEN\n"
    + "        s := s || hours::text || 'h';\n"
    + "    END IF;\n"
    + "    IF mins > 0 THEN\n"
    + "        s := s || mins::text || 'm';\n"
    + "    END IF;\n"
    + "    IF s = '' THEN\n"
    + "        s := '0';\n"
    + "    END IF;\n"
    + "    RETURN s;\n"
    + "END;\n"
    + "$$ LANGUAGE plpgsql;";
