
// Based on: https://wiki.postgresql.org/wiki/Aggregate_Histogram

module.exports.sql
    = " CREATE OR REPLACE FUNCTION\n"
    + "     hist_sfunc (state INTEGER[], val REAL, min REAL, max REAL, nbuckets INTEGER) RETURNS INTEGER[] AS $$\n"
    + " DECLARE\n"
    + "     bucket INTEGER;\n"
    + " BEGIN\n"
    + "     -- Init the array with the correct number of 0's so the caller doesn't see NULLs\n"
    + "     IF state IS NULL THEN\n"
    + "         state := array_fill(0, ARRAY[nbuckets]);\n"
    + "     END IF;\n"
    + "     \n"
    + "     -- width_bucket returns values in the range 0 to (nbuckets + 1)\n"
    + "     -- where 0 and (nbuckets + 1) indicate above- and below-range values\n"
    + "     bucket := width_bucket(val, min, max, nbuckets);\n"
    + "     \n"
    + "     IF bucket IS NOT NULL THEN\n"
    + "         -- clip bucket to allowed range\n"
    + "         bucket := GREATEST(1, LEAST(nbuckets, bucket));\n"
    + "         state[bucket] := state[bucket] + 1;\n"
    + "     END IF;\n"
    + "     \n"
    + "     RETURN state;\n"
    + " END;\n"
    + " $$ LANGUAGE plpgsql IMMUTABLE;\n"
    + " \n"
    + " -- Tell Postgres how to use the new function\n"
    + " DROP AGGREGATE IF EXISTS histogram (REAL, REAL, REAL, INTEGER) CASCADE;\n"
    + " CREATE AGGREGATE histogram (REAL, REAL, REAL, INTEGER) (\n"
    + "     SFUNC = hist_sfunc,\n"
    + "     STYPE = INTEGER[]\n"
    + " );";
