module.exports.sql
    = ' CREATE OR REPLACE VIEW test_stats AS'
    + ' WITH'
    + ' max_student_scores AS ('
    + '     SELECT'
    + '         last_value(t.id)           OVER (PARTITION BY t.id, u.id ORDER BY tsc.score_perc, tsc.date, tsc.id) AS id,'
    + '         last_value(tsc.score_perc) OVER (PARTITION BY t.id, u.id ORDER BY tsc.score_perc, tsc.date, tsc.id) AS score_perc'
    + '     FROM test_scores AS tsc'
    + '     JOIN test_instances AS ti ON (ti.id = tsc.test_instance_id)'
    + '     JOIN tests AS t ON (t.id = ti.test_id)'
    + '     JOIN users AS u ON (u.id = ti.user_id)'
    + '     JOIN enrollments AS e ON (e.user_id = u.id)'
    + '     AND t.deleted_at IS NULL'
    + '     AND e.role = \'Student\''
    + ' )'
    + ' SELECT'
    + '     id,'
    + '     count(score_perc) AS number,'
    + '     min(score_perc) AS min,'
    + '     max(score_perc) AS max,'
    + '     round(avg(score_perc)) AS mean,'
    + '     round(stddev_samp(score_perc)) AS std,'
    + '     percentile_disc(0.5) WITHIN GROUP (ORDER BY score_perc) AS median,'
    + '     count(score_perc <= 0 OR NULL) AS n_zero,'
    + '     count(score_perc >= 100 OR NULL) AS n_hundred,'
    + '     histogram(score_perc, 0, 100, 10) AS score_hist'
    + ' FROM max_student_scores'
    + ' GROUP BY id'
    + ' ;'
