name: Feature Request / Enhancement
description: A request, idea, or new functionality
body:
  - type: textarea
    attributes:
      label: Details
      placeholder: Type your description here...
    validations:
      required: true
type: Enhancement
