import { incoming, outgoing } from './paths.js';
import type { CourseAgentColumn, CourseAgentRelation, ForeignKeyHop } from './types.js';

function col(name: string, pgType: string, sensitive = false): CourseAgentColumn {
  return sensitive ? { name, pgType, sensitive: true } : { name, pgType };
}

const BIGINT = 'bigint';
const BOOL = 'boolean';
const TEXT = 'text';
const TIMESTAMPTZ = 'timestamp with time zone';
const JSONB = 'jsonb';
const FLOAT8 = 'double precision';
const INT = 'integer';
const UUID = 'uuid';
const INTERVAL = 'interval';

function viaAssessmentToCourseInstance(): ForeignKeyHop[] {
  return [outgoing('assessments', 'course_instance_id', 'course_instances')];
}

function viaAssessmentQuestion(): ForeignKeyHop[] {
  return [
    outgoing('assessment_questions', 'assessment_id', 'assessments'),
    ...viaAssessmentToCourseInstance(),
  ];
}

function viaAssessmentInstance(): ForeignKeyHop[] {
  return [
    outgoing('assessment_instances', 'assessment_id', 'assessments'),
    ...viaAssessmentToCourseInstance(),
  ];
}

function viaVariantToCourseInstance(): ForeignKeyHop[] {
  return [outgoing('variants', 'course_instance_id', 'course_instances')];
}

function viaSubmissionToCourseInstance(): ForeignKeyHop[] {
  return [outgoing('submissions', 'variant_id', 'variants'), ...viaVariantToCourseInstance()];
}

function viaInstanceQuestion(): ForeignKeyHop[] {
  return [
    outgoing('instance_questions', 'assessment_instance_id', 'assessment_instances'),
    ...viaAssessmentInstance(),
  ];
}

function viaAccessControlRule(): ForeignKeyHop[] {
  return [
    outgoing('assessment_access_control_rules', 'assessment_id', 'assessments'),
    ...viaAssessmentToCourseInstance(),
  ];
}

function relation(spec: CourseAgentRelation): CourseAgentRelation {
  return spec;
}

export const COURSE_AGENT_RELATIONS: readonly CourseAgentRelation[] = [
  relation({
    name: 'courses',
    description: 'Authorized course metadata needed to interpret configuration.',
    dataKind: 'course_configuration',
    sourceTable: 'courses',
    columns: [
      col('id', BIGINT),
      col('short_name', TEXT),
      col('title', TEXT),
      col('display_timezone', TEXT),
      col('created_at', TIMESTAMPTZ),
      col('example_course', BOOL),
      col('template_course', BOOL),
      col('institution_id', BIGINT),
    ],
    authz: 'course_preview_or_instance_view',
    scopeAnchor: 'course',
    scopePath: { kind: 'single', hops: [] },
    softDeleted: {
      column: 'deleted_at',
      policy: 'exclude',
      reason: 'Deleted courses are not part of the live authoring surface.',
    },
    omittedSensitiveColumns: [
      'sharing_token',
      'repository',
      'path',
      'branch',
      'commit_hash',
      'options',
      'announcement_html',
      'sync_job_sequence_id',
    ],
  }),
  relation({
    name: 'course_instances',
    description: 'Course instances the user is authorized to inspect.',
    dataKind: 'course_instance_configuration',
    sourceTable: 'course_instances',
    columns: [
      col('id', BIGINT),
      col('course_id', BIGINT),
      col('short_name', TEXT),
      col('long_name', TEXT),
      col('display_timezone', TEXT),
      col('assessments_group_by', 'enum_assessment_grouping'),
      col('modern_publishing', BOOL),
      col('publishing_start_date', TIMESTAMPTZ),
      col('publishing_end_date', TIMESTAMPTZ),
      col('self_enrollment_enabled', BOOL),
      col('share_source_publicly', BOOL),
    ],
    authz: 'course_preview_or_instance_view',
    scopeAnchor: 'course_instance',
    scopePath: { kind: 'single', hops: [] },
    softDeleted: {
      column: 'deleted_at',
      policy: 'exclude',
      reason: 'Deleted instances are not part of live configuration.',
    },
    omittedSensitiveColumns: [
      'enrollment_code',
      'sync_job_sequence_id',
      'credit_non_transferable_milli_dollars',
      'credit_transferable_milli_dollars',
    ],
  }),
  relation({
    name: 'questions',
    description: 'Course questions. Instance-only staff see questions used by their instance.',
    dataKind: 'course_configuration',
    sourceTable: 'questions',
    columns: [
      col('id', BIGINT),
      col('course_id', BIGINT),
      col('qid', TEXT),
      col('title', TEXT),
      col('type', 'enum_question_type'),
      col('topic_id', BIGINT),
      col('grading_method', 'enum_grading_method'),
      col('partial_credit', BOOL),
      col('single_variant', BOOL),
      col('draft', BOOL),
      col('share_publicly', BOOL),
      col('share_source_publicly', BOOL),
      col('number', INT),
    ],
    authz: 'course_preview_or_instance_view',
    scopeAnchor: 'course',
    scopePath: { kind: 'single', hops: [outgoing('questions', 'course_id', 'courses')] },
    customScope: { kind: 'question_used_in_authorized_course_instances' },
    softDeleted: {
      column: 'deleted_at',
      policy: 'exclude',
      reason: 'Deleted questions are omitted from configuration queries.',
    },
    omittedSensitiveColumns: ['workspace_environment', 'external_grading_environment', 'options'],
  }),
  relation({
    name: 'tags',
    description: 'Question tags for the authorized course or instance.',
    dataKind: 'course_configuration',
    sourceTable: 'tags',
    columns: [
      col('id', BIGINT),
      col('course_id', BIGINT),
      col('name', TEXT),
      col('color', TEXT),
      col('description', TEXT),
      col('number', INT),
    ],
    authz: 'course_preview_or_instance_view',
    scopeAnchor: 'course',
    scopePath: { kind: 'single', hops: [outgoing('tags', 'course_id', 'courses')] },
    customScope: { kind: 'tag_used_by_authorized_questions' },
    softDeleted: { column: null, policy: 'exclude', reason: 'Tags are not soft-deleted.' },
    omittedSensitiveColumns: [],
  }),
  relation({
    name: 'topics',
    description: 'Question topics for the authorized course or instance.',
    dataKind: 'course_configuration',
    sourceTable: 'topics',
    columns: [
      col('id', BIGINT),
      col('course_id', BIGINT),
      col('name', TEXT),
      col('color', TEXT),
      col('description', TEXT),
      col('number', INT),
    ],
    authz: 'course_preview_or_instance_view',
    scopeAnchor: 'course',
    scopePath: { kind: 'single', hops: [outgoing('topics', 'course_id', 'courses')] },
    customScope: { kind: 'topic_used_by_authorized_questions' },
    softDeleted: { column: null, policy: 'exclude', reason: 'Topics are not soft-deleted.' },
    omittedSensitiveColumns: [],
  }),
  relation({
    name: 'question_tags',
    description: 'Tag assignments. Both the question and tag must belong to the authorized course.',
    dataKind: 'course_configuration',
    sourceTable: 'question_tags',
    columns: [col('id', BIGINT), col('question_id', BIGINT), col('tag_id', BIGINT)],
    authz: 'course_preview_or_instance_view',
    scopeAnchor: 'course',
    scopePath: {
      kind: 'conjunction',
      reason:
        'question_tags has two ownership FKs; both must resolve to the same authorized course.',
      paths: [
        [
          outgoing('question_tags', 'question_id', 'questions'),
          outgoing('questions', 'course_id', 'courses'),
        ],
        [outgoing('question_tags', 'tag_id', 'tags'), outgoing('tags', 'course_id', 'courses')],
      ],
    },
    customScope: { kind: 'question_tag_used_in_authorized_course_instances' },
    softDeleted: { column: null, policy: 'exclude', reason: 'Join rows are not soft-deleted.' },
    omittedSensitiveColumns: [],
  }),
  relation({
    name: 'assessment_sets',
    description: 'Assessment sets. Instance-only staff see sets used by their assessments.',
    dataKind: 'course_configuration',
    sourceTable: 'assessment_sets',
    columns: [
      col('id', BIGINT),
      col('course_id', BIGINT),
      col('name', TEXT),
      col('abbreviation', TEXT),
      col('heading', TEXT),
      col('color', TEXT),
      col('number', INT),
    ],
    authz: 'course_preview_or_instance_view',
    scopeAnchor: 'course',
    scopePath: { kind: 'single', hops: [outgoing('assessment_sets', 'course_id', 'courses')] },
    customScope: { kind: 'assessment_set_used_by_authorized_assessments' },
    softDeleted: {
      column: null,
      policy: 'exclude',
      reason: 'Assessment sets are not soft-deleted.',
    },
    omittedSensitiveColumns: [],
  }),
  relation({
    name: 'assessment_modules',
    description: 'Assessment modules. Instance-only staff see modules used by their assessments.',
    dataKind: 'course_configuration',
    sourceTable: 'assessment_modules',
    columns: [
      col('id', BIGINT),
      col('course_id', BIGINT),
      col('name', TEXT),
      col('heading', TEXT),
      col('number', INT),
    ],
    authz: 'course_preview_or_instance_view',
    scopeAnchor: 'course',
    scopePath: { kind: 'single', hops: [outgoing('assessment_modules', 'course_id', 'courses')] },
    customScope: { kind: 'assessment_module_used_by_authorized_assessments' },
    softDeleted: {
      column: null,
      policy: 'exclude',
      reason: 'Assessment modules are not soft-deleted.',
    },
    omittedSensitiveColumns: [],
  }),
  relation({
    name: 'assessments',
    description: 'Assessments in authorized course instances.',
    dataKind: 'course_instance_configuration',
    sourceTable: 'assessments',
    columns: [
      col('id', BIGINT),
      col('course_instance_id', BIGINT),
      col('tid', TEXT),
      col('title', TEXT),
      col('type', 'enum_assessment_type'),
      col('number', TEXT),
      col('assessment_set_id', BIGINT),
      col('assessment_module_id', BIGINT),
      col('max_points', FLOAT8),
      col('max_bonus_points', FLOAT8),
      col('multiple_instance', BOOL),
      col('team_work', BOOL),
      col('modern_access_control', BOOL),
      col('shuffle_questions', BOOL),
      col('text', TEXT),
    ],
    authz: 'course_preview_or_instance_view',
    scopeAnchor: 'course_instance',
    scopePath: { kind: 'single', hops: viaAssessmentToCourseInstance() },
    softDeleted: {
      column: 'deleted_at',
      policy: 'exclude',
      reason: 'Deleted assessments are omitted from configuration queries.',
    },
    omittedSensitiveColumns: ['obj', 'config', 'sync_job_sequence_id'],
  }),
  relation({
    name: 'zones',
    description: 'Assessment zones.',
    dataKind: 'course_instance_configuration',
    sourceTable: 'zones',
    columns: [
      col('id', BIGINT),
      col('assessment_id', BIGINT),
      col('title', TEXT),
      col('number', INT),
      col('max_points', FLOAT8),
      col('number_choose', INT),
      col('best_questions', INT),
      col('lockpoint', BOOL),
    ],
    authz: 'course_preview_or_instance_view',
    scopeAnchor: 'course_instance',
    scopePath: {
      kind: 'single',
      hops: [outgoing('zones', 'assessment_id', 'assessments'), ...viaAssessmentToCourseInstance()],
    },
    softDeleted: { column: null, policy: 'exclude', reason: 'Zones are not soft-deleted.' },
    omittedSensitiveColumns: [],
  }),
  relation({
    name: 'alternative_groups',
    description: 'Alternative question groups within zones.',
    dataKind: 'course_instance_configuration',
    sourceTable: 'alternative_groups',
    columns: [
      col('id', BIGINT),
      col('assessment_id', BIGINT),
      col('zone_id', BIGINT),
      col('number', INT),
      col('number_choose', INT),
    ],
    authz: 'course_preview_or_instance_view',
    scopeAnchor: 'course_instance',
    scopePath: {
      kind: 'single',
      hops: [
        outgoing('alternative_groups', 'assessment_id', 'assessments'),
        ...viaAssessmentToCourseInstance(),
      ],
    },
    softDeleted: {
      column: null,
      policy: 'exclude',
      reason: 'Alternative groups are not soft-deleted.',
    },
    omittedSensitiveColumns: [],
  }),
  relation({
    name: 'assessment_questions',
    description: 'Questions placed on assessments, including rubric links.',
    dataKind: 'course_instance_configuration',
    sourceTable: 'assessment_questions',
    columns: [
      col('id', BIGINT),
      col('assessment_id', BIGINT),
      col('question_id', BIGINT),
      col('alternative_group_id', BIGINT),
      col('number', INT),
      col('max_points', FLOAT8),
      col('max_auto_points', FLOAT8),
      col('max_manual_points', FLOAT8),
      col('init_points', FLOAT8),
      col('manual_rubric_id', BIGINT),
      col('tries_per_variant', INT),
      col('allow_real_time_grading', BOOL),
    ],
    authz: 'course_preview_or_instance_view',
    scopeAnchor: 'course_instance',
    scopePath: { kind: 'single', hops: viaAssessmentQuestion() },
    softDeleted: {
      column: 'deleted_at',
      policy: 'exclude',
      reason: 'Deleted assessment questions are omitted from configuration.',
    },
    omittedSensitiveColumns: [],
  }),
  relation({
    name: 'assessment_tools',
    description: 'Tools attached to an assessment or a zone. Ownership is exclusive-or.',
    dataKind: 'course_instance_configuration',
    sourceTable: 'assessment_tools',
    columns: [
      col('id', BIGINT),
      col('assessment_id', BIGINT),
      col('zone_id', BIGINT),
      col('tool', TEXT),
      col('enabled', BOOL),
      col('settings', JSONB),
    ],
    authz: 'course_preview_or_instance_view',
    scopeAnchor: 'course_instance',
    scopePath: {
      kind: 'disjunction',
      reason: 'assessment_tools rows belong to either an assessment or a zone, never both.',
      alternatives: [
        [
          outgoing('assessment_tools', 'assessment_id', 'assessments'),
          ...viaAssessmentToCourseInstance(),
        ],
        [
          outgoing('assessment_tools', 'zone_id', 'zones'),
          outgoing('zones', 'assessment_id', 'assessments'),
          ...viaAssessmentToCourseInstance(),
        ],
      ],
    },
    softDeleted: {
      column: null,
      policy: 'exclude',
      reason: 'Assessment tools are not soft-deleted.',
    },
    omittedSensitiveColumns: [],
  }),
  relation({
    name: 'course_instance_access_rules',
    description: 'Legacy course-instance access windows.',
    dataKind: 'course_instance_configuration',
    sourceTable: 'course_instance_access_rules',
    columns: [
      col('id', BIGINT),
      col('course_instance_id', BIGINT),
      col('number', INT),
      col('start_date', TIMESTAMPTZ),
      col('end_date', TIMESTAMPTZ),
      col('institution', TEXT),
    ],
    authz: 'course_preview_or_instance_view',
    scopeAnchor: 'course_instance',
    scopePath: {
      kind: 'single',
      hops: [outgoing('course_instance_access_rules', 'course_instance_id', 'course_instances')],
    },
    softDeleted: { column: null, policy: 'exclude', reason: 'Access rules are not soft-deleted.' },
    omittedSensitiveColumns: ['uids'],
  }),
  relation({
    name: 'assessment_access_rules',
    description: 'Legacy per-assessment access rules. Passwords are omitted.',
    dataKind: 'course_instance_configuration',
    sourceTable: 'assessment_access_rules',
    columns: [
      col('id', BIGINT),
      col('assessment_id', BIGINT),
      col('number', INT),
      col('mode', 'enum_mode'),
      col('start_date', TIMESTAMPTZ),
      col('end_date', TIMESTAMPTZ),
      col('credit', INT),
      col('time_limit_min', INT),
      col('active', BOOL),
      col('show_closed_assessment', BOOL),
      col('show_closed_assessment_score', BOOL),
      col('exam_uuid', UUID),
    ],
    authz: 'course_preview_or_instance_view',
    scopeAnchor: 'course_instance',
    scopePath: {
      kind: 'single',
      hops: [
        outgoing('assessment_access_rules', 'assessment_id', 'assessments'),
        ...viaAssessmentToCourseInstance(),
      ],
    },
    softDeleted: { column: null, policy: 'exclude', reason: 'Access rules are not soft-deleted.' },
    omittedSensitiveColumns: ['password', 'seb_config', 'uids'],
  }),
  relation({
    name: 'assessment_access_control_rules',
    description: 'Modern assessment access-control rules. Passwords are omitted.',
    dataKind: 'course_instance_configuration',
    sourceTable: 'assessment_access_control_rules',
    columns: [
      col('id', BIGINT),
      col('assessment_id', BIGINT),
      col('number', INT),
      col('uuid', UUID),
      col('target_type', 'enum_assessment_access_control_target_type'),
      col('before_release_listed', BOOL),
      col('date_control_release_date', TIMESTAMPTZ),
      col('date_control_due_date', TIMESTAMPTZ),
      col('date_control_due_credit', INT),
      col('date_control_duration_minutes', INT),
      col('date_control_after_last_deadline_credit', INT),
      col('date_control_after_last_deadline_allow_submissions', BOOL),
      col('after_complete_questions_hidden', BOOL),
      col('after_complete_score_hidden', BOOL),
    ],
    authz: 'course_preview_or_instance_view',
    scopeAnchor: 'course_instance',
    scopePath: { kind: 'single', hops: viaAccessControlRule() },
    softDeleted: {
      column: null,
      policy: 'exclude',
      reason: 'Access-control rules are not soft-deleted.',
    },
    omittedSensitiveColumns: ['date_control_password'],
  }),
  relation({
    name: 'assessment_access_control_enrollments',
    description: 'Enrollment targets for modern access-control rules.',
    dataKind: 'course_instance_configuration',
    sourceTable: 'assessment_access_control_enrollments',
    columns: [
      col('id', BIGINT),
      col('assessment_access_control_rule_id', BIGINT),
      col('enrollment_id', BIGINT),
      col('target_type', 'enum_assessment_access_control_target_type'),
    ],
    authz: 'course_preview_or_instance_view',
    scopeAnchor: 'course_instance',
    scopePath: {
      kind: 'single',
      hops: [
        outgoing(
          'assessment_access_control_enrollments',
          'assessment_access_control_rule_id',
          'assessment_access_control_rules',
        ),
        ...viaAccessControlRule(),
      ],
    },
    softDeleted: { column: null, policy: 'exclude', reason: 'Join rows are not soft-deleted.' },
    omittedSensitiveColumns: [],
  }),
  relation({
    name: 'assessment_access_control_student_labels',
    description: 'Student-label targets for modern access-control rules.',
    dataKind: 'course_instance_configuration',
    sourceTable: 'assessment_access_control_student_labels',
    columns: [
      col('id', BIGINT),
      col('assessment_access_control_rule_id', BIGINT),
      col('student_label_id', BIGINT),
      col('target_type', 'enum_assessment_access_control_target_type'),
    ],
    authz: 'course_preview_or_instance_view',
    scopeAnchor: 'course_instance',
    scopePath: {
      kind: 'single',
      hops: [
        outgoing(
          'assessment_access_control_student_labels',
          'assessment_access_control_rule_id',
          'assessment_access_control_rules',
        ),
        ...viaAccessControlRule(),
      ],
    },
    softDeleted: { column: null, policy: 'exclude', reason: 'Join rows are not soft-deleted.' },
    omittedSensitiveColumns: [],
  }),
  relation({
    name: 'assessment_access_control_early_deadlines',
    description: 'Early-deadline exceptions on modern access-control rules.',
    dataKind: 'course_instance_configuration',
    sourceTable: 'assessment_access_control_early_deadlines',
    columns: [
      col('id', BIGINT),
      col('assessment_access_control_rule_id', BIGINT),
      col('date', TIMESTAMPTZ),
      col('credit', INT),
    ],
    authz: 'course_preview_or_instance_view',
    scopeAnchor: 'course_instance',
    scopePath: {
      kind: 'single',
      hops: [
        outgoing(
          'assessment_access_control_early_deadlines',
          'assessment_access_control_rule_id',
          'assessment_access_control_rules',
        ),
        ...viaAccessControlRule(),
      ],
    },
    softDeleted: { column: null, policy: 'exclude', reason: 'Deadline rows are not soft-deleted.' },
    omittedSensitiveColumns: [],
  }),
  relation({
    name: 'assessment_access_control_late_deadlines',
    description: 'Late-deadline exceptions on modern access-control rules.',
    dataKind: 'course_instance_configuration',
    sourceTable: 'assessment_access_control_late_deadlines',
    columns: [
      col('id', BIGINT),
      col('assessment_access_control_rule_id', BIGINT),
      col('date', TIMESTAMPTZ),
      col('credit', INT),
    ],
    authz: 'course_preview_or_instance_view',
    scopeAnchor: 'course_instance',
    scopePath: {
      kind: 'single',
      hops: [
        outgoing(
          'assessment_access_control_late_deadlines',
          'assessment_access_control_rule_id',
          'assessment_access_control_rules',
        ),
        ...viaAccessControlRule(),
      ],
    },
    softDeleted: { column: null, policy: 'exclude', reason: 'Deadline rows are not soft-deleted.' },
    omittedSensitiveColumns: [],
  }),
  relation({
    name: 'assessment_access_control_prairietest_exams',
    description: 'PrairieTest exam bindings on modern access-control rules.',
    dataKind: 'course_instance_configuration',
    sourceTable: 'assessment_access_control_prairietest_exams',
    columns: [
      col('id', BIGINT),
      col('assessment_access_control_rule_id', BIGINT),
      col('uuid', UUID),
      col('read_only', BOOL),
      col('after_complete_questions_hidden', BOOL),
      col('after_complete_score_hidden', BOOL),
    ],
    authz: 'course_preview_or_instance_view',
    scopeAnchor: 'course_instance',
    scopePath: {
      kind: 'single',
      hops: [
        outgoing(
          'assessment_access_control_prairietest_exams',
          'assessment_access_control_rule_id',
          'assessment_access_control_rules',
        ),
        ...viaAccessControlRule(),
      ],
    },
    softDeleted: {
      column: null,
      policy: 'exclude',
      reason: 'PrairieTest bindings are not soft-deleted.',
    },
    omittedSensitiveColumns: [],
  }),
  relation({
    name: 'student_labels',
    description: 'Instructor-defined student labels for a course instance.',
    dataKind: 'course_instance_configuration',
    sourceTable: 'student_labels',
    columns: [
      col('id', BIGINT),
      col('course_instance_id', BIGINT),
      col('name', TEXT),
      col('color', TEXT),
      col('uuid', UUID),
    ],
    authz: 'course_preview_or_instance_view',
    scopeAnchor: 'course_instance',
    scopePath: {
      kind: 'single',
      hops: [outgoing('student_labels', 'course_instance_id', 'course_instances')],
    },
    softDeleted: {
      column: null,
      policy: 'exclude',
      reason: 'Student labels are not soft-deleted.',
    },
    omittedSensitiveColumns: [],
  }),
  relation({
    name: 'rubrics',
    description: 'Manual-grading rubrics reachable from authorized assessment questions.',
    dataKind: 'course_instance_configuration',
    sourceTable: 'rubrics',
    columns: [
      col('id', BIGINT),
      col('starting_points', FLOAT8),
      col('min_points', FLOAT8),
      col('max_extra_points', FLOAT8),
      col('replace_auto_points', BOOL),
      col('grader_guidelines', TEXT),
      col('created_at', TIMESTAMPTZ),
      col('modified_at', TIMESTAMPTZ),
      col('deleted_at', TIMESTAMPTZ),
    ],
    authz: 'course_preview_or_instance_view',
    scopeAnchor: 'course_instance',
    scopePath: {
      kind: 'single',
      hops: [
        incoming('rubrics', 'assessment_questions', 'manual_rubric_id'),
        ...viaAssessmentQuestion(),
      ],
    },
    softDeleted: {
      column: 'deleted_at',
      policy: 'include',
      reason: 'Historical grades still reference deleted rubrics.',
    },
    omittedSensitiveColumns: [],
  }),
  relation({
    name: 'rubric_items',
    description: 'Items on manual-grading rubrics.',
    dataKind: 'course_instance_configuration',
    sourceTable: 'rubric_items',
    columns: [
      col('id', BIGINT),
      col('rubric_id', BIGINT),
      col('number', INT),
      col('points', FLOAT8),
      col('description', 'character varying(100)'),
      col('explanation', 'character varying(10000)'),
      col('grader_note', 'character varying(10000)'),
      col('always_show_to_students', BOOL),
      col('key_binding', 'character varying(30)'),
      col('deleted_at', TIMESTAMPTZ),
    ],
    authz: 'course_preview_or_instance_view',
    scopeAnchor: 'course_instance',
    scopePath: {
      kind: 'single',
      hops: [
        outgoing('rubric_items', 'rubric_id', 'rubrics'),
        incoming('rubrics', 'assessment_questions', 'manual_rubric_id'),
        ...viaAssessmentQuestion(),
      ],
    },
    softDeleted: {
      column: 'deleted_at',
      policy: 'include',
      reason: 'Historical grades still reference deleted rubric items.',
    },
    omittedSensitiveColumns: [],
  }),
  relation({
    name: 'team_configs',
    description: 'Team assessment configuration.',
    dataKind: 'course_instance_configuration',
    sourceTable: 'team_configs',
    columns: [
      col('id', BIGINT),
      col('course_instance_id', BIGINT),
      col('assessment_id', BIGINT),
      col('name', TEXT),
      col('minimum', INT),
      col('maximum', INT),
      col('has_roles', BOOL),
      col('student_authz_create', BOOL),
      col('student_authz_join', BOOL),
      col('student_authz_leave', BOOL),
      col('student_authz_choose_name', BOOL),
    ],
    authz: 'course_preview_or_instance_view',
    scopeAnchor: 'course_instance',
    scopePath: {
      kind: 'single',
      hops: [outgoing('team_configs', 'course_instance_id', 'course_instances')],
    },
    softDeleted: {
      column: 'deleted_at',
      policy: 'exclude',
      reason: 'Deleted team configs are omitted from configuration.',
    },
    omittedSensitiveColumns: [],
  }),
  relation({
    name: 'team_roles',
    description: 'Named roles for team assessments.',
    dataKind: 'course_instance_configuration',
    sourceTable: 'team_roles',
    columns: [
      col('id', BIGINT),
      col('assessment_id', BIGINT),
      col('role_name', TEXT),
      col('minimum', INT),
      col('maximum', INT),
      col('can_assign_roles', BOOL),
    ],
    authz: 'course_preview_or_instance_view',
    scopeAnchor: 'course_instance',
    scopePath: {
      kind: 'single',
      hops: [
        outgoing('team_roles', 'assessment_id', 'assessments'),
        ...viaAssessmentToCourseInstance(),
      ],
    },
    softDeleted: { column: null, policy: 'exclude', reason: 'Team roles are not soft-deleted.' },
    omittedSensitiveColumns: [],
  }),
  relation({
    name: 'assessment_question_role_permissions',
    description: 'Per-role view/submit permissions on assessment questions.',
    dataKind: 'course_instance_configuration',
    sourceTable: 'assessment_question_role_permissions',
    columns: [
      col('assessment_question_id', BIGINT),
      col('team_role_id', BIGINT),
      col('can_view', BOOL),
      col('can_submit', BOOL),
    ],
    authz: 'course_preview_or_instance_view',
    scopeAnchor: 'course_instance',
    scopePath: {
      kind: 'single',
      hops: [
        outgoing(
          'assessment_question_role_permissions',
          'assessment_question_id',
          'assessment_questions',
        ),
        ...viaAssessmentQuestion(),
      ],
    },
    softDeleted: {
      column: null,
      policy: 'exclude',
      reason: 'Permission rows are not soft-deleted.',
    },
    omittedSensitiveColumns: [],
  }),
  relation({
    name: 'enrollments',
    description: 'Student enrollments in the authorized course instance.',
    dataKind: 'student_data',
    sourceTable: 'enrollments',
    columns: [
      col('id', BIGINT),
      col('user_id', BIGINT),
      col('course_instance_id', BIGINT),
      col('status', 'enum_enrollment_status'),
      col('created_at', TIMESTAMPTZ),
      col('first_joined_at', TIMESTAMPTZ),
      col('is_guest', BOOL),
    ],
    authz: 'course_instance_permission_view',
    scopeAnchor: 'course_instance',
    scopePath: {
      kind: 'single',
      hops: [outgoing('enrollments', 'course_instance_id', 'course_instances')],
    },
    softDeleted: { column: null, policy: 'exclude', reason: 'Enrollments are not soft-deleted.' },
    omittedSensitiveColumns: [
      'pending_email',
      'pending_lti13_sub',
      'pending_lti13_course_instance_id',
    ],
  }),
  relation({
    name: 'enrolled_users',
    description: 'Identity fields for users enrolled in the authorized course instance.',
    dataKind: 'student_data',
    sourceTable: 'users',
    columns: [
      col('id', BIGINT),
      col('uid', TEXT),
      col('name', TEXT),
      col('uin', TEXT),
      col('email', 'character varying(255)'),
    ],
    authz: 'course_instance_permission_view',
    scopeAnchor: 'course_instance',
    scopePath: {
      kind: 'single',
      hops: [
        incoming('users', 'enrollments', 'user_id'),
        outgoing('enrollments', 'course_instance_id', 'course_instances'),
      ],
    },
    softDeleted: { column: null, policy: 'exclude', reason: 'Users are not soft-deleted.' },
    omittedSensitiveColumns: [
      'stripe_customer_id',
      'lti_user_id',
      'lti_context_id',
      'lti_course_instance_id',
    ],
  }),
  relation({
    name: 'student_label_enrollments',
    description: 'Assignments of student labels to enrollments.',
    dataKind: 'student_data',
    sourceTable: 'student_label_enrollments',
    columns: [col('id', BIGINT), col('student_label_id', BIGINT), col('enrollment_id', BIGINT)],
    authz: 'course_instance_permission_view',
    scopeAnchor: 'course_instance',
    scopePath: {
      kind: 'single',
      hops: [
        outgoing('student_label_enrollments', 'enrollment_id', 'enrollments'),
        outgoing('enrollments', 'course_instance_id', 'course_instances'),
      ],
    },
    softDeleted: { column: null, policy: 'exclude', reason: 'Join rows are not soft-deleted.' },
    omittedSensitiveColumns: [],
  }),
  relation({
    name: 'teams',
    description: 'Student teams in the authorized course instance.',
    dataKind: 'student_data',
    sourceTable: 'teams',
    columns: [
      col('id', BIGINT),
      col('course_instance_id', BIGINT),
      col('team_config_id', BIGINT),
      col('name', TEXT),
      col('date', TIMESTAMPTZ),
    ],
    authz: 'course_instance_permission_view',
    scopeAnchor: 'course_instance',
    scopePath: {
      kind: 'single',
      hops: [outgoing('teams', 'course_instance_id', 'course_instances')],
    },
    softDeleted: {
      column: 'deleted_at',
      policy: 'include',
      reason: 'Deleted teams remain referenced by historical assessment instances.',
    },
    omittedSensitiveColumns: ['join_code'],
  }),
  relation({
    name: 'team_users',
    description: 'Team membership.',
    dataKind: 'student_data',
    sourceTable: 'team_users',
    columns: [col('team_id', BIGINT), col('user_id', BIGINT), col('team_config_id', BIGINT)],
    authz: 'course_instance_permission_view',
    scopeAnchor: 'course_instance',
    scopePath: {
      kind: 'single',
      hops: [
        outgoing('team_users', 'team_id', 'teams'),
        outgoing('teams', 'course_instance_id', 'course_instances'),
      ],
    },
    softDeleted: {
      column: null,
      policy: 'exclude',
      reason: 'Membership rows are not soft-deleted.',
    },
    omittedSensitiveColumns: [],
  }),
  relation({
    name: 'team_user_roles',
    description: 'Assigned roles within a team.',
    dataKind: 'student_data',
    sourceTable: 'team_user_roles',
    columns: [
      col('id', BIGINT),
      col('team_id', BIGINT),
      col('user_id', BIGINT),
      col('team_role_id', BIGINT),
    ],
    authz: 'course_instance_permission_view',
    scopeAnchor: 'course_instance',
    scopePath: {
      kind: 'single',
      hops: [
        outgoing('team_user_roles', 'team_id', 'teams'),
        outgoing('teams', 'course_instance_id', 'course_instances'),
      ],
    },
    softDeleted: {
      column: null,
      policy: 'exclude',
      reason: 'Role assignment rows are not soft-deleted.',
    },
    omittedSensitiveColumns: [],
  }),
  relation({
    name: 'assessment_instances',
    description: 'Student or team assessment attempts.',
    dataKind: 'student_data',
    sourceTable: 'assessment_instances',
    columns: [
      col('id', BIGINT),
      col('assessment_id', BIGINT),
      col('user_id', BIGINT),
      col('team_id', BIGINT),
      col('number', INT),
      col('open', BOOL),
      col('date', TIMESTAMPTZ),
      col('closed_at', TIMESTAMPTZ),
      col('duration', INTERVAL),
      col('points', FLOAT8),
      col('score_perc', FLOAT8),
      col('max_points', FLOAT8),
      col('include_in_statistics', BOOL),
    ],
    authz: 'course_instance_permission_view',
    scopeAnchor: 'course_instance',
    scopePath: { kind: 'single', hops: viaAssessmentInstance() },
    softDeleted: {
      column: null,
      policy: 'exclude',
      reason: 'Assessment instances are not soft-deleted.',
    },
    omittedSensitiveColumns: [],
  }),
  relation({
    name: 'instance_questions',
    description: 'Per-student question state inside an assessment instance.',
    dataKind: 'student_data',
    sourceTable: 'instance_questions',
    columns: [
      col('id', BIGINT),
      col('assessment_instance_id', BIGINT),
      col('assessment_question_id', BIGINT),
      col('points', FLOAT8),
      col('score_perc', FLOAT8),
      col('auto_points', FLOAT8),
      col('manual_points', FLOAT8),
      col('status', 'enum_instance_question_status'),
      col('open', BOOL),
      col('number_attempts', INT),
      col('requires_manual_grading', BOOL),
      col('assigned_grader', BIGINT),
      col('last_grader', BIGINT),
    ],
    authz: 'course_instance_permission_view',
    scopeAnchor: 'course_instance',
    scopePath: { kind: 'single', hops: viaInstanceQuestion() },
    softDeleted: {
      column: null,
      policy: 'exclude',
      reason: 'Instance questions are not soft-deleted.',
    },
    omittedSensitiveColumns: [],
  }),
  relation({
    name: 'student_variants',
    description: 'Generated variants for student or team activity in a course instance.',
    dataKind: 'student_data',
    sourceTable: 'variants',
    columns: [
      col('id', BIGINT),
      col('course_id', BIGINT),
      col('course_instance_id', BIGINT),
      col('question_id', BIGINT),
      col('instance_question_id', BIGINT),
      col('user_id', BIGINT),
      col('team_id', BIGINT),
      col('number', INT),
      col('open', BOOL),
      col('date', TIMESTAMPTZ),
      col('duration', INTERVAL),
      col('num_tries', INT),
      col('broken', BOOL),
    ],
    authz: 'course_instance_permission_view',
    scopeAnchor: 'course_instance',
    scopePath: { kind: 'single', hops: viaVariantToCourseInstance() },
    customScope: {
      kind: 'not_null',
      constraints: [{ table: 'variants', column: 'course_instance_id' }],
    },
    softDeleted: { column: null, policy: 'exclude', reason: 'Variants are not soft-deleted.' },
    omittedSensitiveColumns: ['params', 'true_answer', 'options', 'variant_seed', 'preferences'],
  }),
  relation({
    name: 'preview_variants',
    description: 'Instructor preview variants with no course instance (course configuration).',
    dataKind: 'course_configuration',
    sourceTable: 'variants',
    columns: [
      col('id', BIGINT),
      col('course_id', BIGINT),
      col('question_id', BIGINT),
      col('date', TIMESTAMPTZ),
      col('open', BOOL),
      col('broken', BOOL),
    ],
    authz: 'course_permission_preview',
    scopeAnchor: 'course',
    scopePath: { kind: 'single', hops: [outgoing('variants', 'course_id', 'courses')] },
    customScope: {
      kind: 'is_null',
      constraints: [{ table: 'variants', column: 'course_instance_id' }],
    },
    softDeleted: { column: null, policy: 'exclude', reason: 'Variants are not soft-deleted.' },
    omittedSensitiveColumns: ['params', 'true_answer', 'options', 'variant_seed'],
  }),
  relation({
    name: 'submissions',
    description: 'Student submissions for variants in the authorized course instance.',
    dataKind: 'student_data',
    sourceTable: 'submissions',
    columns: [
      col('id', BIGINT),
      col('variant_id', BIGINT),
      col('date', TIMESTAMPTZ),
      col('credit', INT),
      col('mode', 'enum_mode'),
      col('gradable', BOOL),
      col('broken', BOOL),
      col('correct', BOOL),
      col('score', FLOAT8),
      col('v2_score', FLOAT8),
      col('graded_at', TIMESTAMPTZ),
      col('is_ai_graded', BOOL),
      col('manual_rubric_grading_id', BIGINT),
    ],
    authz: 'course_instance_permission_view',
    scopeAnchor: 'course_instance',
    scopePath: { kind: 'single', hops: viaSubmissionToCourseInstance() },
    softDeleted: { column: null, policy: 'exclude', reason: 'Submissions are not soft-deleted.' },
    omittedSensitiveColumns: [
      'submitted_answer',
      'raw_submitted_answer',
      'true_answer',
      'params',
      'feedback',
      'partial_scores',
      'format_errors',
    ],
  }),
  relation({
    name: 'grading_jobs',
    description: 'Grading-job results. Follows submissions to instance-scoped variants.',
    dataKind: 'student_data',
    sourceTable: 'grading_jobs',
    columns: [
      col('id', BIGINT),
      col('submission_id', BIGINT),
      col('date', TIMESTAMPTZ),
      col('grading_method', 'enum_grading_method'),
      col('gradable', BOOL),
      col('correct', BOOL),
      col('score', FLOAT8),
      col('auto_points', FLOAT8),
      col('manual_points', FLOAT8),
      col('graded_at', TIMESTAMPTZ),
      col('graded_by', BIGINT),
      col('manual_rubric_grading_id', BIGINT),
      col('deleted_at', TIMESTAMPTZ),
    ],
    authz: 'course_instance_permission_view',
    scopeAnchor: 'course_instance',
    scopePath: {
      kind: 'single',
      hops: [
        outgoing('grading_jobs', 'submission_id', 'submissions'),
        ...viaSubmissionToCourseInstance(),
      ],
    },
    softDeleted: {
      column: 'deleted_at',
      policy: 'include',
      reason: 'Deleted grading jobs remain useful for historical score analysis.',
    },
    omittedSensitiveColumns: ['output', 's3_bucket', 's3_root_key', 'feedback', 'partial_scores'],
  }),
  relation({
    name: 'rubric_gradings',
    description: 'Applied rubric scores on submissions or grading jobs.',
    dataKind: 'student_data',
    sourceTable: 'rubric_gradings',
    columns: [
      col('id', BIGINT),
      col('rubric_id', BIGINT),
      col('computed_points', FLOAT8),
      col('adjust_points', FLOAT8),
      col('starting_points', FLOAT8),
      col('min_points', FLOAT8),
      col('max_extra_points', FLOAT8),
    ],
    authz: 'course_instance_permission_view',
    scopeAnchor: 'course_instance',
    scopePath: {
      kind: 'disjunction',
      reason:
        'rubric_gradings are referenced from submissions or grading_jobs; neither FK is authoritative alone.',
      alternatives: [
        [
          incoming('rubric_gradings', 'submissions', 'manual_rubric_grading_id'),
          ...viaSubmissionToCourseInstance(),
        ],
        [
          incoming('rubric_gradings', 'grading_jobs', 'manual_rubric_grading_id'),
          outgoing('grading_jobs', 'submission_id', 'submissions'),
          ...viaSubmissionToCourseInstance(),
        ],
      ],
    },
    softDeleted: {
      column: null,
      policy: 'exclude',
      reason: 'Rubric grading rows are not soft-deleted.',
    },
    omittedSensitiveColumns: [],
  }),
  relation({
    name: 'rubric_grading_items',
    description: 'Per-item scores within an applied rubric grading.',
    dataKind: 'student_data',
    sourceTable: 'rubric_grading_items',
    columns: [
      col('id', BIGINT),
      col('rubric_grading_id', BIGINT),
      col('rubric_item_id', BIGINT),
      col('score', FLOAT8),
      col('points', FLOAT8),
      col('description', 'character varying(100)'),
    ],
    authz: 'course_instance_permission_view',
    scopeAnchor: 'course_instance',
    scopePath: {
      kind: 'disjunction',
      reason: 'Applied rubric items follow rubric_gradings through submissions or grading_jobs.',
      alternatives: [
        [
          outgoing('rubric_grading_items', 'rubric_grading_id', 'rubric_gradings'),
          incoming('rubric_gradings', 'submissions', 'manual_rubric_grading_id'),
          ...viaSubmissionToCourseInstance(),
        ],
        [
          outgoing('rubric_grading_items', 'rubric_grading_id', 'rubric_gradings'),
          incoming('rubric_gradings', 'grading_jobs', 'manual_rubric_grading_id'),
          outgoing('grading_jobs', 'submission_id', 'submissions'),
          ...viaSubmissionToCourseInstance(),
        ],
      ],
    },
    softDeleted: {
      column: null,
      policy: 'exclude',
      reason: 'Rubric grading item rows are not soft-deleted.',
    },
    omittedSensitiveColumns: [],
  }),
  relation({
    name: 'assessment_score_logs',
    description: 'Historical assessment-instance scores.',
    dataKind: 'student_data',
    sourceTable: 'assessment_score_logs',
    columns: [
      col('id', BIGINT),
      col('assessment_instance_id', BIGINT),
      col('date', TIMESTAMPTZ),
      col('points', FLOAT8),
      col('score_perc', FLOAT8),
      col('max_points', FLOAT8),
    ],
    authz: 'course_instance_permission_view',
    scopeAnchor: 'course_instance',
    scopePath: {
      kind: 'single',
      hops: [
        outgoing('assessment_score_logs', 'assessment_instance_id', 'assessment_instances'),
        ...viaAssessmentInstance(),
      ],
    },
    softDeleted: { column: null, policy: 'exclude', reason: 'Score logs are not soft-deleted.' },
    omittedSensitiveColumns: [],
  }),
  relation({
    name: 'question_score_logs',
    description: 'Historical instance-question scores.',
    dataKind: 'student_data',
    sourceTable: 'question_score_logs',
    columns: [
      col('id', BIGINT),
      col('instance_question_id', BIGINT),
      col('grading_job_id', BIGINT),
      col('date', TIMESTAMPTZ),
      col('points', FLOAT8),
      col('score_perc', FLOAT8),
      col('auto_points', FLOAT8),
      col('manual_points', FLOAT8),
    ],
    authz: 'course_instance_permission_view',
    scopeAnchor: 'course_instance',
    scopePath: {
      kind: 'single',
      hops: [
        outgoing('question_score_logs', 'instance_question_id', 'instance_questions'),
        ...viaInstanceQuestion(),
      ],
    },
    softDeleted: { column: null, policy: 'exclude', reason: 'Score logs are not soft-deleted.' },
    omittedSensitiveColumns: [],
  }),
  relation({
    name: 'assessment_state_logs',
    description: 'Open/close history for assessment instances.',
    dataKind: 'student_data',
    sourceTable: 'assessment_state_logs',
    columns: [
      col('id', BIGINT),
      col('assessment_instance_id', BIGINT),
      col('date', TIMESTAMPTZ),
      col('open', BOOL),
      col('date_limit', TIMESTAMPTZ),
    ],
    authz: 'course_instance_permission_view',
    scopeAnchor: 'course_instance',
    scopePath: {
      kind: 'single',
      hops: [
        outgoing('assessment_state_logs', 'assessment_instance_id', 'assessment_instances'),
        ...viaAssessmentInstance(),
      ],
    },
    softDeleted: { column: null, policy: 'exclude', reason: 'State logs are not soft-deleted.' },
    omittedSensitiveColumns: [],
  }),
  relation({
    name: 'page_view_logs',
    description: 'Student page-view activity. Rows without a course instance are excluded.',
    dataKind: 'student_data',
    sourceTable: 'page_view_logs',
    columns: [
      col('id', BIGINT),
      col('user_id', BIGINT),
      col('course_instance_id', BIGINT),
      col('assessment_id', BIGINT),
      col('assessment_instance_id', BIGINT),
      col('question_id', BIGINT),
      col('variant_id', BIGINT),
      col('date', TIMESTAMPTZ),
      col('page_type', TEXT),
    ],
    authz: 'course_instance_permission_view',
    scopeAnchor: 'course_instance',
    scopePath: {
      kind: 'single',
      hops: [outgoing('page_view_logs', 'course_instance_id', 'course_instances')],
    },
    customScope: {
      kind: 'not_null',
      constraints: [{ table: 'page_view_logs', column: 'course_instance_id' }],
    },
    softDeleted: {
      column: null,
      policy: 'exclude',
      reason: 'Page view logs are not soft-deleted.',
    },
    omittedSensitiveColumns: ['path', 'client_fingerprint_id'],
  }),
  relation({
    name: 'current_pages',
    description:
      'Latest page each student is viewing. Rows without a course instance are excluded.',
    dataKind: 'student_data',
    sourceTable: 'current_pages',
    columns: [
      col('id', BIGINT),
      col('user_id', BIGINT),
      col('course_instance_id', BIGINT),
      col('assessment_id', BIGINT),
      col('assessment_instance_id', BIGINT),
      col('question_id', BIGINT),
      col('variant_id', BIGINT),
      col('date', TIMESTAMPTZ),
      col('page_type', TEXT),
    ],
    authz: 'course_instance_permission_view',
    scopeAnchor: 'course_instance',
    scopePath: {
      kind: 'single',
      hops: [outgoing('current_pages', 'course_instance_id', 'course_instances')],
    },
    customScope: {
      kind: 'not_null',
      constraints: [{ table: 'current_pages', column: 'course_instance_id' }],
    },
    softDeleted: {
      column: null,
      policy: 'exclude',
      reason: 'Current page rows are not soft-deleted.',
    },
    omittedSensitiveColumns: ['path'],
  }),
  relation({
    name: 'course_issues',
    description: 'Course-level issue reports that are not tied to a course instance.',
    dataKind: 'course_configuration',
    sourceTable: 'issues',
    columns: [
      col('id', BIGINT),
      col('course_id', BIGINT),
      col('question_id', BIGINT),
      col('date', TIMESTAMPTZ),
      col('open', BOOL),
      col('manually_reported', BOOL),
      col('course_caused', BOOL),
      col('instructor_message', TEXT),
    ],
    authz: 'course_permission_view',
    scopeAnchor: 'course',
    scopePath: { kind: 'single', hops: [outgoing('issues', 'course_id', 'courses')] },
    customScope: {
      kind: 'is_null',
      constraints: [{ table: 'issues', column: 'course_instance_id' }],
    },
    softDeleted: { column: null, policy: 'exclude', reason: 'Issues are not soft-deleted.' },
    omittedSensitiveColumns: ['system_data', 'course_data', 'student_message'],
  }),
  relation({
    name: 'instance_issues',
    description: 'Issue reports tied to an authorized course instance.',
    dataKind: 'student_data',
    sourceTable: 'issues',
    columns: [
      col('id', BIGINT),
      col('course_id', BIGINT),
      col('course_instance_id', BIGINT),
      col('assessment_id', BIGINT),
      col('question_id', BIGINT),
      col('instance_question_id', BIGINT),
      col('variant_id', BIGINT),
      col('user_id', BIGINT),
      col('date', TIMESTAMPTZ),
      col('open', BOOL),
      col('manually_reported', BOOL),
      col('course_caused', BOOL),
      col('instructor_message', TEXT),
    ],
    authz: 'course_instance_permission_view',
    scopeAnchor: 'course_instance',
    scopePath: {
      kind: 'single',
      hops: [outgoing('issues', 'course_instance_id', 'course_instances')],
    },
    customScope: {
      kind: 'not_null',
      constraints: [{ table: 'issues', column: 'course_instance_id' }],
    },
    softDeleted: { column: null, policy: 'exclude', reason: 'Issues are not soft-deleted.' },
    omittedSensitiveColumns: ['system_data', 'course_data', 'student_message'],
  }),
];

export function getCourseAgentRelation(name: string): CourseAgentRelation | undefined {
  return COURSE_AGENT_RELATIONS.find((relation) => relation.name === name);
}
