CREATE TABLE "foods" ("food" text, "colour" text);

INSERT INTO
  "foods" ("food", "colour")
VALUES
  ('Apple', 'Red'),
  ('Banana', 'Yellow'),
  ('Grapes', 'Purple'),
  ('Orange', 'Orange'),
  ('Lemon', 'Yellow'),
  ('Strawberry', 'Red'),
  ('Blueberry', 'Blue'),
  ('Kiwi', 'Green'),
  ('Watermelon', 'Green'),
  ('Pineapple', 'Yellow'),
  ('Avocado', 'Green'),
  ('Cherry', 'Red'),
  ('Mango', 'Yellow'),
  ('Plum', 'Purple'),
  ('Peach', 'Orange'),
  ('Raspberry', 'Red'),
  ('Blackberry', 'Black'),
  ('Cantaloupe', 'Orange'),
  ('Cucumber', 'Green'),
  ('Tomato', 'Red'),
  ('Pumpkin', 'Orange'),
  ('Carrot', 'Orange'),
  ('Sweet Potato', 'Orange'),
  ('Onion', 'Purple'),
  ('Bell Pepper', 'Red'),
  ('Garlic', 'White'),
  ('Eggplant', 'Purple'),
  ('Zucchini', 'Green'),
  ('Lettuce', 'Green'),
  ('Spinach', 'Green'),
  ('Broccoli', 'Green'),
  ('Cauliflower', 'White'),
  ('Beetroot', 'Purple'),
  ('Celery', 'Green'),
  ('Radish', 'Red'),
  ('Asparagus', 'Green'),
  ('Pomegranate', 'Red'),
  ('Pear', 'Green'),
  ('Fig', 'Purple'),
  ('Lychee', 'Red'),
  ('Dragon Fruit', 'Pink'),
  ('Cabbage', 'Purple'),
  ('Mushroom', 'Brown'),
  ('Ginger', 'Beige'),
  ('Potato', 'Brown'),
  ('Corn', 'Yellow'),
  ('Chili Pepper', 'Red'),
  ('Persimmon', 'Orange'),
  ('Passion Fruit', 'Purple'),
  ('Apricot', 'Orange'),
  ('Gooseberry', 'Green');
