import * as z from 'zod/v4';

import { booleanFormat, integerFormat, numberFormat } from '../helpers.ts';
import type { ElementChildSchema, ElementSchemaModule } from '../types.ts';

const plDrawingAttributesSchema = z.looseObject({
  'allow-blank': booleanFormat().optional(),
  'angle-tol': numberFormat().optional(),
  'answers-name': z.string().optional(),
  'aria-description': z.string().optional(),
  'aria-label': z.string().optional(),
  'disregard-extra-elements': booleanFormat().optional(),
  gradable: booleanFormat().optional(),
  'grid-size': integerFormat().optional(),
  height: numberFormat().optional(),
  'hide-answer-panel': booleanFormat().optional(),
  'show-score': booleanFormat().optional(),
  'show-tolerance-hint': booleanFormat().optional(),
  'snap-to-grid': booleanFormat().optional(),
  tol: numberFormat().optional(),
  'tolerance-hint': z.string().optional(),
  weight: integerFormat().optional(),
  width: numberFormat().optional(),
});

// pl-drawing renders a fixed set of built-in "drawing object" tags inside its
// answer/initial/group containers. Each maps to a class in
// `apps/prairielearn/elements/pl-drawing/elements.py` whose `get_attributes()`
// defines its (all-optional) attribute contract. Element extensions can register
// additional object tags at runtime, so the containers also set
// `allowAdditionalChildren: true`.
const drawingObject = (shape: z.ZodRawShape): ElementChildSchema => ({
  schema: z.toJSONSchema(z.object(shape).strict(), { target: 'draft-04' }),
});

const drawingObjectChildren: Record<string, ElementChildSchema> = {
  'pl-3pointrod': drawingObject({
    color: z.string().optional(),
    'draw-pin': z.string().optional(),
    label1: z.string().optional(),
    label2: z.string().optional(),
    label3: z.string().optional(),
    offsetx1: numberFormat().optional(),
    offsetx2: numberFormat().optional(),
    offsetx3: numberFormat().optional(),
    offsety1: numberFormat().optional(),
    offsety2: numberFormat().optional(),
    offsety3: numberFormat().optional(),
    'stroke-color': z.string().optional(),
    'stroke-width': numberFormat().optional(),
    width: numberFormat().optional(),
    x1: numberFormat().optional(),
    x2: numberFormat().optional(),
    x3: numberFormat().optional(),
    y1: numberFormat().optional(),
    y2: numberFormat().optional(),
    y3: numberFormat().optional(),
  }),
  'pl-4pointrod': drawingObject({
    color: z.string().optional(),
    'draw-pin': z.string().optional(),
    label1: z.string().optional(),
    label2: z.string().optional(),
    label3: z.string().optional(),
    label4: z.string().optional(),
    offsetx1: numberFormat().optional(),
    offsetx2: numberFormat().optional(),
    offsetx3: numberFormat().optional(),
    offsetx4: numberFormat().optional(),
    offsety1: numberFormat().optional(),
    offsety2: numberFormat().optional(),
    offsety3: numberFormat().optional(),
    offsety4: numberFormat().optional(),
    'stroke-color': z.string().optional(),
    'stroke-width': numberFormat().optional(),
    width: numberFormat().optional(),
    x1: numberFormat().optional(),
    x2: numberFormat().optional(),
    x3: numberFormat().optional(),
    x4: numberFormat().optional(),
    y1: numberFormat().optional(),
    y2: numberFormat().optional(),
    y3: numberFormat().optional(),
    y4: numberFormat().optional(),
  }),
  'pl-arc': drawingObject({
    'dashed-size': numberFormat().optional(),
    'end-angle': numberFormat().optional(),
    opacity: numberFormat().optional(),
    radius: numberFormat().optional(),
    'start-angle': numberFormat().optional(),
    'stroke-color': z.string().optional(),
    'stroke-width': numberFormat().optional(),
    x1: numberFormat().optional(),
    y1: numberFormat().optional(),
  }),
  'pl-arc-dimensions': drawingObject({
    'arrow-head-length': numberFormat().optional(),
    'arrow-head-width': numberFormat().optional(),
    'draw-center': booleanFormat().optional(),
    'draw-end-arrow': booleanFormat().optional(),
    'draw-start-arrow': booleanFormat().optional(),
    'end-angle': numberFormat().optional(),
    'end-support-line': booleanFormat().optional(),
    label: z.string().optional(),
    offsetx: numberFormat().optional(),
    offsety: numberFormat().optional(),
    radius: numberFormat().optional(),
    'start-angle': numberFormat().optional(),
    'start-support-line': booleanFormat().optional(),
    'stroke-color': z.string().optional(),
    'stroke-width': numberFormat().optional(),
    x1: numberFormat().optional(),
    y1: numberFormat().optional(),
  }),
  'pl-arc-vector': drawingObject({
    'anchor-is-tail': z.string().optional(),
    'arrow-head-length': numberFormat().optional(),
    'arrow-head-width': numberFormat().optional(),
    'clockwise-direction': booleanFormat().optional(),
    color: z.string().optional(),
    'disregard-sense': booleanFormat().optional(),
    'draw-center': z.string().optional(),
    'draw-error-box': booleanFormat().optional(),
    'end-angle': numberFormat().optional(),
    label: z.string().optional(),
    offsetx: numberFormat().optional(),
    offsety: numberFormat().optional(),
    'optional-grading': booleanFormat().optional(),
    radius: numberFormat().optional(),
    'start-angle': numberFormat().optional(),
    'stroke-width': numberFormat().optional(),
    x1: numberFormat().optional(),
    y1: numberFormat().optional(),
  }),
  'pl-axes': drawingObject({
    color: z.string().optional(),
    'grid-label': z.string().optional(),
    'label-x': z.string().optional(),
    'label-y': z.string().optional(),
    'offsetx-label-x': numberFormat().optional(),
    'offsetx-label-y': numberFormat().optional(),
    'offsety-label-x': numberFormat().optional(),
    'offsety-label-y': numberFormat().optional(),
    origin: z.string().optional(),
    'stroke-width': numberFormat().optional(),
    'supporting-lines': z.string().optional(),
    xneg: numberFormat().optional(),
    xpos: numberFormat().optional(),
    yneg: numberFormat().optional(),
    ypos: numberFormat().optional(),
  }),
  'pl-battery': drawingObject({
    angle: numberFormat().optional(),
    'font-size': numberFormat().optional(),
    height: numberFormat().optional(),
    interval: numberFormat().optional(),
    label: z.string().optional(),
    offsetx: numberFormat().optional(),
    offsety: numberFormat().optional(),
    'stroke-color': z.string().optional(),
    'stroke-width': numberFormat().optional(),
    width: numberFormat().optional(),
    x1: numberFormat().optional(),
    x2: numberFormat().optional(),
    y1: numberFormat().optional(),
    y2: numberFormat().optional(),
  }),
  'pl-capacitor': drawingObject({
    angle: numberFormat().optional(),
    'font-size': numberFormat().optional(),
    height: numberFormat().optional(),
    interval: numberFormat().optional(),
    label: z.string().optional(),
    offsetx: numberFormat().optional(),
    offsety: numberFormat().optional(),
    polarized: booleanFormat().optional(),
    'stroke-color': z.string().optional(),
    'stroke-width': numberFormat().optional(),
    width: numberFormat().optional(),
    x1: numberFormat().optional(),
    x2: numberFormat().optional(),
    y1: numberFormat().optional(),
    y2: numberFormat().optional(),
  }),
  'pl-circle': drawingObject({
    color: z.string().optional(),
    label: z.string().optional(),
    offsetx: numberFormat().optional(),
    offsety: numberFormat().optional(),
    opacity: numberFormat().optional(),
    radius: numberFormat().optional(),
    'stroke-color': z.string().optional(),
    'stroke-width': numberFormat().optional(),
    x1: numberFormat().optional(),
    y1: numberFormat().optional(),
  }),
  'pl-clamped': drawingObject({
    angle: numberFormat().optional(),
    color: z.string().optional(),
    height: numberFormat().optional(),
    label: z.string().optional(),
    offsetx: numberFormat().optional(),
    offsety: numberFormat().optional(),
    'stroke-width': numberFormat().optional(),
    width: numberFormat().optional(),
    x1: numberFormat().optional(),
    y1: numberFormat().optional(),
  }),
  'pl-coil': drawingObject({
    angle: numberFormat().optional(),
    'draw-pin': booleanFormat().optional(),
    height: numberFormat().optional(),
    'stroke-color': z.string().optional(),
    'stroke-width': numberFormat().optional(),
    width: numberFormat().optional(),
    x1: numberFormat().optional(),
    x2: numberFormat().optional(),
    y1: numberFormat().optional(),
    y2: numberFormat().optional(),
  }),
  'pl-collar-rod': drawingObject({
    color: z.string().optional(),
    'draw-collar-end1': booleanFormat().optional(),
    'draw-collar-end2': booleanFormat().optional(),
    'draw-pin': z.string().optional(),
    h1: numberFormat().optional(),
    h2: numberFormat().optional(),
    label1: z.string().optional(),
    label2: z.string().optional(),
    offsetx1: numberFormat().optional(),
    offsetx2: numberFormat().optional(),
    offsety1: numberFormat().optional(),
    offsety2: numberFormat().optional(),
    'stroke-color': z.string().optional(),
    'stroke-width': numberFormat().optional(),
    w1: numberFormat().optional(),
    w2: numberFormat().optional(),
    width: numberFormat().optional(),
    x1: numberFormat().optional(),
    x2: numberFormat().optional(),
    y1: numberFormat().optional(),
    y2: numberFormat().optional(),
  }),
  'pl-controlled-curved-line': drawingObject({
    color: z.string().optional(),
    'draw-error-box': booleanFormat().optional(),
    'handle-radius': numberFormat().optional(),
    'offset-control-tol-x': numberFormat().optional(),
    'offset-control-tol-y': numberFormat().optional(),
    'offset-tol-x': numberFormat().optional(),
    'offset-tol-y': numberFormat().optional(),
    'stroke-width': numberFormat().optional(),
    x1: numberFormat().optional(),
    x2: numberFormat().optional(),
    x3: numberFormat().optional(),
    y1: numberFormat().optional(),
    y2: numberFormat().optional(),
    y3: numberFormat().optional(),
  }),
  'pl-controlled-line': drawingObject({
    color: z.string().optional(),
    'draw-error-box': booleanFormat().optional(),
    'handle-radius': numberFormat().optional(),
    'offset-control-tol-x': z.string().optional(),
    'offset-control-tol-y': z.string().optional(),
    'offset-tol-x': numberFormat().optional(),
    'offset-tol-y': numberFormat().optional(),
    'stroke-width': numberFormat().optional(),
    x1: numberFormat().optional(),
    x2: numberFormat().optional(),
    x3: z.string().optional(),
    y1: numberFormat().optional(),
    y2: numberFormat().optional(),
    y3: z.string().optional(),
  }),
  'pl-coordinates': drawingObject({
    angle: numberFormat().optional(),
    'arrow-head-length': numberFormat().optional(),
    'arrow-head-width': numberFormat().optional(),
    color: z.string().optional(),
    label: z.string().optional(),
    'label-x': z.string().optional(),
    'label-y': z.string().optional(),
    offsetx: numberFormat().optional(),
    'offsetx-label-x': numberFormat().optional(),
    'offsetx-label-y': numberFormat().optional(),
    offsety: numberFormat().optional(),
    'offsety-label-x': numberFormat().optional(),
    'offsety-label-y': numberFormat().optional(),
    'stroke-width': numberFormat().optional(),
    width: numberFormat().optional(),
    x1: numberFormat().optional(),
    y1: numberFormat().optional(),
  }),
  'pl-dimensions': drawingObject({
    angle: numberFormat().optional(),
    'arrow-head-length': numberFormat().optional(),
    'arrow-head-width': numberFormat().optional(),
    'dim-offset': numberFormat().optional(),
    'dim-offset-angle': numberFormat().optional(),
    'draw-end-arrow': z.string().optional(),
    'draw-start-arrow': z.string().optional(),
    'end-support-line': booleanFormat().optional(),
    label: z.string().optional(),
    offsetx: numberFormat().optional(),
    offsety: numberFormat().optional(),
    'start-support-line': booleanFormat().optional(),
    'stroke-color': z.string().optional(),
    'stroke-width': numberFormat().optional(),
    width: numberFormat().optional(),
    x1: numberFormat().optional(),
    x2: numberFormat().optional(),
    y1: numberFormat().optional(),
    y2: numberFormat().optional(),
  }),
  'pl-distributed-load': drawingObject({
    'anchor-is-tail': booleanFormat().optional(),
    angle: numberFormat().optional(),
    'arrow-head-length': numberFormat().optional(),
    'arrow-head-width': numberFormat().optional(),
    color: z.string().optional(),
    'disregard-sense': booleanFormat().optional(),
    'draw-error-box': booleanFormat().optional(),
    label1: z.string().optional(),
    label2: z.string().optional(),
    'offset-backward': numberFormat().optional(),
    'offset-forward': numberFormat().optional(),
    offsetx1: numberFormat().optional(),
    offsetx2: numberFormat().optional(),
    offsety1: numberFormat().optional(),
    offsety2: numberFormat().optional(),
    'optional-grading': booleanFormat().optional(),
    spacing: numberFormat().optional(),
    'stroke-width': numberFormat().optional(),
    w1: numberFormat().optional(),
    w2: numberFormat().optional(),
    width: numberFormat().optional(),
    x1: numberFormat().optional(),
    y1: numberFormat().optional(),
  }),
  'pl-double-headed-vector': drawingObject({
    'anchor-is-tail': booleanFormat().optional(),
    angle: numberFormat().optional(),
    'arrow-head-length': numberFormat().optional(),
    'arrow-head-width': numberFormat().optional(),
    color: z.string().optional(),
    'disregard-sense': booleanFormat().optional(),
    'draw-error-box': booleanFormat().optional(),
    label: z.string().optional(),
    'offset-backward': numberFormat().optional(),
    'offset-forward': numberFormat().optional(),
    offsetx: numberFormat().optional(),
    offsety: numberFormat().optional(),
    'optional-grading': booleanFormat().optional(),
    'stroke-width': numberFormat().optional(),
    width: numberFormat().optional(),
    x1: numberFormat().optional(),
    y1: numberFormat().optional(),
  }),
  'pl-fixed-pin': drawingObject({
    angle: numberFormat().optional(),
    color: z.string().optional(),
    'draw-ground': z.string().optional(),
    'draw-pin': z.string().optional(),
    height: numberFormat().optional(),
    label: z.string().optional(),
    offsetx: numberFormat().optional(),
    offsety: numberFormat().optional(),
    'stroke-color': z.string().optional(),
    'stroke-width': numberFormat().optional(),
    width: numberFormat().optional(),
    x1: numberFormat().optional(),
    y1: numberFormat().optional(),
  }),
  'pl-graph-line': drawingObject({
    color: z.string().optional(),
    'draw-error-box': booleanFormat().optional(),
    'end-gradients': z.string().optional(),
    'end-points': z.string().optional(),
    'offset-control-tol-x': numberFormat().optional(),
    'offset-control-tol-y': numberFormat().optional(),
    'offset-tol-x': numberFormat().optional(),
    'offset-tol-y': numberFormat().optional(),
    origin: z.string().optional(),
    'stroke-width': numberFormat().optional(),
  }),
  'pl-inductor': drawingObject({
    angle: numberFormat().optional(),
    'font-size': numberFormat().optional(),
    height: numberFormat().optional(),
    interval: numberFormat().optional(),
    label: z.string().optional(),
    offsetx: numberFormat().optional(),
    offsety: numberFormat().optional(),
    'stroke-color': z.string().optional(),
    'stroke-width': numberFormat().optional(),
    width: numberFormat().optional(),
    x1: numberFormat().optional(),
    x2: numberFormat().optional(),
    y1: numberFormat().optional(),
    y2: numberFormat().optional(),
  }),
  'pl-line': drawingObject({
    angle: numberFormat().optional(),
    'dashed-size': numberFormat().optional(),
    opacity: numberFormat().optional(),
    'stroke-color': z.string().optional(),
    'stroke-width': numberFormat().optional(),
    width: numberFormat().optional(),
    x1: numberFormat().optional(),
    x2: numberFormat().optional(),
    y1: numberFormat().optional(),
    y2: numberFormat().optional(),
  }),
  'pl-paired-vector': drawingObject({
    'anchor-is-tail': booleanFormat().optional(),
    angle1: numberFormat().optional(),
    angle2: numberFormat().optional(),
    'arrow-head-length': numberFormat().optional(),
    'arrow-head-width': numberFormat().optional(),
    color: z.string().optional(),
    'disregard-sense': booleanFormat().optional(),
    'draw-error-box': booleanFormat().optional(),
    label: z.string().optional(),
    'offset-backward': numberFormat().optional(),
    'offset-forward': numberFormat().optional(),
    offsetx: numberFormat().optional(),
    offsety: numberFormat().optional(),
    'optional-grading': booleanFormat().optional(),
    'stroke-width': numberFormat().optional(),
    weight: z.string().optional(),
    width: numberFormat().optional(),
    x1: numberFormat().optional(),
    x2: numberFormat().optional(),
    y1: numberFormat().optional(),
    y2: numberFormat().optional(),
  }),
  'pl-point': drawingObject({
    color: z.string().optional(),
    'draw-error-box': booleanFormat().optional(),
    label: z.string().optional(),
    offsetx: numberFormat().optional(),
    offsety: numberFormat().optional(),
    opacity: numberFormat().optional(),
    radius: numberFormat().optional(),
    x1: numberFormat().optional(),
    y1: numberFormat().optional(),
  }),
  'pl-polygon': drawingObject({
    color: z.string().optional(),
    opacity: numberFormat().optional(),
    plist: z.string().optional(),
    'stroke-color': z.string().optional(),
    'stroke-width': numberFormat().optional(),
  }),
  'pl-pulley': drawingObject({
    'alternative-path': booleanFormat().optional(),
    color: z.string().optional(),
    label: z.string().optional(),
    offsetx: numberFormat().optional(),
    offsety: numberFormat().optional(),
    radius: numberFormat().optional(),
    'stroke-color': z.string().optional(),
    'stroke-width': numberFormat().optional(),
    x1: numberFormat().optional(),
    x2: numberFormat().optional(),
    x3: numberFormat().optional(),
    y1: numberFormat().optional(),
    y2: numberFormat().optional(),
    y3: numberFormat().optional(),
  }),
  'pl-rectangle': drawingObject({
    angle: numberFormat().optional(),
    color: z.string().optional(),
    height: numberFormat().optional(),
    opacity: numberFormat().optional(),
    'stroke-color': z.string().optional(),
    'stroke-width': numberFormat().optional(),
    width: numberFormat().optional(),
    x1: numberFormat().optional(),
    y1: numberFormat().optional(),
  }),
  'pl-resistor': drawingObject({
    angle: numberFormat().optional(),
    'font-size': numberFormat().optional(),
    height: numberFormat().optional(),
    interval: numberFormat().optional(),
    label: z.string().optional(),
    offsetx: numberFormat().optional(),
    offsety: numberFormat().optional(),
    'stroke-color': z.string().optional(),
    'stroke-width': numberFormat().optional(),
    width: numberFormat().optional(),
    x1: numberFormat().optional(),
    x2: numberFormat().optional(),
    y1: numberFormat().optional(),
    y2: numberFormat().optional(),
  }),
  'pl-rod': drawingObject({
    color: z.string().optional(),
    'draw-pin': z.string().optional(),
    label1: z.string().optional(),
    label2: z.string().optional(),
    offsetx1: numberFormat().optional(),
    offsetx2: numberFormat().optional(),
    offsety1: numberFormat().optional(),
    offsety2: numberFormat().optional(),
    'stroke-color': z.string().optional(),
    'stroke-width': numberFormat().optional(),
    width: numberFormat().optional(),
    x1: numberFormat().optional(),
    x2: numberFormat().optional(),
    y1: numberFormat().optional(),
    y2: numberFormat().optional(),
  }),
  'pl-roller': drawingObject({
    angle: numberFormat().optional(),
    color: z.string().optional(),
    'draw-ground': z.string().optional(),
    'draw-pin': z.string().optional(),
    height: numberFormat().optional(),
    label: z.string().optional(),
    offsetx: numberFormat().optional(),
    offsety: numberFormat().optional(),
    'stroke-color': z.string().optional(),
    'stroke-width': numberFormat().optional(),
    width: numberFormat().optional(),
    x1: numberFormat().optional(),
    y1: numberFormat().optional(),
  }),
  'pl-spring': drawingObject({
    angle: numberFormat().optional(),
    'draw-pin': booleanFormat().optional(),
    height: numberFormat().optional(),
    interval: numberFormat().optional(),
    'stroke-color': z.string().optional(),
    'stroke-width': numberFormat().optional(),
    width: numberFormat().optional(),
    x1: numberFormat().optional(),
    x2: numberFormat().optional(),
    y1: numberFormat().optional(),
    y2: numberFormat().optional(),
  }),
  'pl-switch': drawingObject({
    angle: numberFormat().optional(),
    'draw-pin': booleanFormat().optional(),
    'font-size': numberFormat().optional(),
    interval: numberFormat().optional(),
    label: z.string().optional(),
    offsetx: numberFormat().optional(),
    offsety: numberFormat().optional(),
    'stroke-color': z.string().optional(),
    'stroke-width': numberFormat().optional(),
    'switch-angle': numberFormat().optional(),
    width: numberFormat().optional(),
    x1: numberFormat().optional(),
    x2: numberFormat().optional(),
    y1: numberFormat().optional(),
    y2: numberFormat().optional(),
  }),
  'pl-text': drawingObject({
    'font-size': numberFormat().optional(),
    label: z.string().optional(),
    latex: booleanFormat().optional(),
    offsetx: numberFormat().optional(),
    offsety: numberFormat().optional(),
    x1: numberFormat().optional(),
    y1: numberFormat().optional(),
  }),
  'pl-triangle': drawingObject({
    color: z.string().optional(),
    opacity: numberFormat().optional(),
    'stroke-color': z.string().optional(),
    'stroke-width': numberFormat().optional(),
    x1: numberFormat().optional(),
    x2: numberFormat().optional(),
    x3: numberFormat().optional(),
    y1: numberFormat().optional(),
    y2: numberFormat().optional(),
    y3: numberFormat().optional(),
  }),
  'pl-vector': drawingObject({
    'anchor-is-tail': booleanFormat().optional(),
    angle: numberFormat().optional(),
    'arrow-head-length': numberFormat().optional(),
    'arrow-head-width': numberFormat().optional(),
    color: z.string().optional(),
    'disregard-sense': booleanFormat().optional(),
    'draw-error-box': booleanFormat().optional(),
    label: z.string().optional(),
    'offset-backward': numberFormat().optional(),
    'offset-forward': numberFormat().optional(),
    offsetx: numberFormat().optional(),
    offsety: numberFormat().optional(),
    'optional-grading': booleanFormat().optional(),
    'stroke-width': numberFormat().optional(),
    width: numberFormat().optional(),
    x1: numberFormat().optional(),
    y1: numberFormat().optional(),
  }),
};

const drawingGroupSchema = z.toJSONSchema(
  z.object({ visible: booleanFormat().optional() }).strict(),
  { target: 'draft-04' },
);

// Groups can nest. The nested entry registers pl-drawing-group as a valid parent
// of itself; objects inside a nested group pass via allowAdditionalChildren.
const nestedDrawingGroupChild: ElementChildSchema = {
  schema: drawingGroupSchema,
  allowAdditionalChildren: true,
};

const plDrawingGroupChild: ElementChildSchema = {
  schema: drawingGroupSchema,
  children: {
    'pl-drawing-group': nestedDrawingGroupChild,
    ...drawingObjectChildren,
  },
  // Also holds drawing-object child tags defined by element extensions.
  allowAdditionalChildren: true,
};

const drawingItemsContainerChild: ElementChildSchema = {
  schema: z.toJSONSchema(z.object({ 'draw-error-box': booleanFormat().optional() }).strict(), {
    target: 'draft-04',
  }),
  children: {
    'pl-drawing-group': plDrawingGroupChild,
    ...drawingObjectChildren,
  },
  // Also holds drawing-object child tags defined by element extensions.
  allowAdditionalChildren: true,
};

const plDrawingButtonChild: ElementChildSchema = {
  // pl-drawing-button skips attribute validation in Python because it accepts the
  // attributes of whatever drawing object its `type` names, so allow any attribute.
  schema: z.toJSONSchema(z.looseObject({ type: z.string() }), { target: 'draft-04' }),
};

const plControlsGroupChild: ElementChildSchema = {
  schema: z.toJSONSchema(z.object({ label: z.string().optional() }).strict(), {
    target: 'draft-04',
  }),
  children: {
    'pl-drawing-button': plDrawingButtonChild,
  },
};

const plControlsChild: ElementChildSchema = {
  schema: z.toJSONSchema(z.object({}).strict(), { target: 'draft-04' }),
  children: {
    'pl-controls-group': plControlsGroupChild,
    'pl-drawing-button': plDrawingButtonChild,
  },
};

export const element: ElementSchemaModule = {
  tag: 'pl-drawing',
  schema: z.toJSONSchema(plDrawingAttributesSchema, { target: 'draft-04' }),
  children: {
    'pl-controls': plControlsChild,
    'pl-drawing-answer': drawingItemsContainerChild,
    'pl-drawing-initial': drawingItemsContainerChild,
  },
};
