import matplotlib.pyplot as plt
import io

def file(data):
    if data['filename']=='my-data':
        return 'This data is generated by code.'
    elif data['filename']=='my-mpl-figure':
        plt.plot([1,2,3],[3,4,-2])
        buf = io.BytesIO()
        plt.savefig(buf,format='png')
        return buf
