import math

import prairielearn as pl

MEASUREMENT_NAMES = ["D", "L", "x1", "Tb", "T1"]


def generate(data):
    data["params"]["k"] = 20

    # Reference values for the physical measurements. Each student takes their
    # own measurements, so submissions are graded against these references with
    # generous tolerances (set on each pl-number-input in question.html).
    data["correct_answers"]["D"] = 0.01
    data["correct_answers"]["L"] = 0.3
    data["correct_answers"]["x1"] = 0.03
    data["correct_answers"]["Tb"] = 85
    data["correct_answers"]["T1"] = 55


def parse(data):
    # Sanity-check the recorded measurements. Marking implausible values as
    # format errors keeps the submission from being graded (and from using up
    # one of the student's attempts).
    for name in [*MEASUREMENT_NAMES, "qf"]:
        var = data["submitted_answers"].get(name)
        if var is None:
            data["format_errors"][name] = f"Variable {name} is not defined"
        elif name in ["Tb", "T1"]:
            if var > 100:
                data["format_errors"][name] = f"Temperature {name} looks too high."
            elif var < 10:
                data["format_errors"][name] = f"Temperature {name} looks too low."
        elif name in ["D", "L", "x1"] and var > 0.5:
            data["format_errors"][name] = (
                f"Dimension {name} is outside the range of acceptable values for this experiment. Check your units?"
            )


def grade(data):
    # The expected value of qf is computed from the student's own recorded
    # measurements, not from the reference values, so any answer consistent
    # with the recorded data is accepted.
    submitted = data["submitted_answers"]
    Ac = math.pi * submitted["D"] ** 2 / 4
    qf = (
        -data["params"]["k"]
        * Ac
        * (submitted["T1"] - submitted["Tb"])
        / submitted["x1"]
    )

    if math.isclose(submitted["qf"], qf, rel_tol=1e-3):
        data["partial_scores"]["qf"] = {"score": 1, "weight": 1}
    else:
        data["partial_scores"]["qf"] = {"score": 0, "weight": 1}
        data["feedback"]["qf"] = (
            "Your value for $q_f$ is not consistent with your recorded measurements."
        )

    pl.set_weighted_score_data(data)


def test(data):
    if data["test_type"] == "invalid":
        return

    is_correct = data["test_type"] == "correct"
    correct = data["correct_answers"]

    if not is_correct:
        # The incorrect Tb generated by pl-number-input's own test function can
        # fall outside the range accepted by parse(), so replace it with a
        # fixed in-range (but still incorrect) value. The value needs enough
        # decimal digits that pl-number-input does not attach its insufficient
        # precision warning, which the expected test data will not contain.
        data["raw_submitted_answers"]["Tb"] = "59.5234234234242342423"

    # qf has no fixed correct answer, so pl-number-input defers generating its
    # test data to this function.
    Ac = math.pi * correct["D"] ** 2 / 4
    qf = -data["params"]["k"] * Ac * (correct["T1"] - correct["Tb"]) / correct["x1"]
    offset = 0 if is_correct else 1
    data["raw_submitted_answers"]["qf"] = str(qf + offset)

    score = 1 if is_correct else 0
    data["partial_scores"]["qf"] = {"score": score, "weight": 1}
    data["score"] = score
