#!/usr/bin/env python3
"""
Generate JS redirect code for the legacy `elements` docs page.

This script hard-codes a mapping from the old anchor IDs used on
`docs/elements.md` (e.g. `#pl-number-input-element`) to new URLs,
so that the old single-page `elements.md` can become a thin JS
redirect shim without breaking existing links.

Usage:
  python docs/scripts/gen_elements_redirect_js.py > /tmp/elements-redirect.js
  # Then paste the output into a <script>...</script> block in docs/elements.md
"""

from __future__ import annotations

import json
from textwrap import dedent

# Mapping from old hash IDs on `elements.md` (without the leading '#')
# to their new URLs. The convention here is:
#   "pl-<element-name>-element" -> "/elements/pl-<element-name>/"
# You can adjust any of these targets later if you decide to group
# elements differently or rename pages.
REDIRECTS: dict[str, str] = {
    # Default when there is no hash on the old URL:
    "": "/elements/index/",
    # Submission elements
    "pl-big-o-input-element": "/elements/pl-big-o-input/",
    "pl-checkbox-element": "/elements/pl-checkbox/",
    "pl-excalidraw-element": "/elements/pl-excalidraw/",
    "pl-file-editor-element": "/elements/pl-file-editor/",
    "pl-file-upload-element": "/elements/pl-file-upload/",
    "pl-image-capture-element": "/elements/pl-image-capture/",
    "pl-integer-input-element": "/elements/pl-integer-input/",
    "pl-matching-element": "/elements/pl-matching/",
    "pl-matrix-component-input-element": "/elements/pl-matrix-component-input/",
    "pl-matrix-input-element": "/elements/pl-matrix-input/",
    "pl-multiple-choice-element": "/elements/pl-multiple-choice/",
    "pl-number-input-element": "/elements/pl-number-input/",
    "pl-order-blocks-element": "/elements/pl-order-blocks/",
    "pl-rich-text-editor-element": "/elements/pl-rich-text-editor/",
    "pl-string-input-element": "/elements/pl-string-input/",
    "pl-symbolic-input-element": "/elements/pl-symbolic-input/",
    "pl-units-input-element": "/elements/pl-units-input/",
    # Decorative elements
    "pl-card-element": "/elements/pl-card/",
    "pl-code-element": "/elements/pl-code/",
    "pl-dataframe-element": "/elements/pl-dataframe/",
    "pl-drawing-element": "/elements/pl-drawing/",
    "pl-external-grader-variables-element": "/elements/pl-external-grader-variables/",
    "pl-figure-element": "/elements/pl-figure/",
    "pl-file-download-element": "/elements/pl-file-download/",
    "pl-file-preview-element": "/elements/pl-file-preview/",
    "pl-graph-element": "/elements/pl-graph/",
    "pl-matrix-latex-element": "/elements/pl-matrix-latex/",
    "pl-overlay-element": "/elements/pl-overlay/",
    "pl-python-variable-element": "/elements/pl-python-variable/",
    "pl-variable-output-element": "/elements/pl-variable-output/",
    "pl-template-element": "/elements/pl-template/",
    "pl-xss-safe-element": "/elements/pl-xss-safe/",
    # Conditional elements
    "pl-answer-panel-element": "/elements/pl-answer-panel/",
    "pl-external-grader-results-element": "/elements/pl-external-grader-results/",
    "pl-hide-in-panel-element": "/elements/pl-hide-in-panel/",
    "pl-hide-in-manual-grading-element": "/elements/pl-hide-in-manual-grading/",
    "pl-hidden-hints-element": "/elements/pl-hidden-hints/",
    "pl-manual-grading-only-element": "/elements/pl-manual-grading-only/",
    "pl-question-panel-element": "/elements/pl-question-panel/",
    "pl-submission-panel-element": "/elements/pl-submission-panel/",
    # Deprecated elements
    "pl-dropdown-element": "/elements/pl-dropdown/",
    "pl-prairiedraw-figure-element": "/elements/pl-prairiedraw-figure/",
    "pl-threejs-element": "/elements/pl-threejs/",
    "pl-variable-score-element": "/elements/pl-variable-score/",
}


def build_js(redirects: dict[str, str]) -> str:
    """Return the JS redirect shim as a string."""
    mapping_js = json.dumps(redirects, sort_keys=True, indent=2)

    # Wrap in an IIFE so we don't leak globals on the docs page.
    return dedent(
        f"""\
        (function() {{
          // Mapping from old hash IDs on `elements.md` to new URLs.
          // Generated by docs/scripts/gen_elements_redirect_js.py
          var redirects = {mapping_js};

          var loc = window.location;
          var hash = loc.hash.replace(/^#/, "");

          // Prefer exact hash match; fall back to "" (no-hash) default if present.
          var hasExact = Object.prototype.hasOwnProperty.call(redirects, hash);
          var target = hasExact ? redirects[hash] : redirects[""];

          if (!target) {{
            return; // no redirect configured
          }}

          var url = new URL(target, loc.origin);

          // Preserve any query string (?foo=bar) from the original URL.
          if (loc.search) {{
            url.search = loc.search;
          }}

          // Avoid redirect loops.
          if (url.href === loc.href) {{
            return;
          }}

          window.location.replace(url.href);
        }})();"""
    )


def main() -> None:
    print(build_js(REDIRECTS))


if __name__ == "__main__":
    main()
