CREATE OR REPLACE FUNCTION unnest_2d_1d(ANYARRAY, OUT a ANYARRAY)
    RETURNS SETOF ANYARRAY AS
$func$
BEGIN
    FOREACH a SLICE 1 IN ARRAY $1 LOOP
        RETURN NEXT;
    END LOOP;
END
$func$  LANGUAGE plpgsql IMMUTABLE STRICT;