CREATE TABLE IF NOT EXISTS course_instances (
    id SERIAL PRIMARY KEY,
    course_id INTEGER NOT NULL REFERENCES courses ON DELETE CASCADE ON UPDATE CASCADE,
    semester_id INTEGER NOT NULL REFERENCES semesters ON DELETE CASCADE ON UPDATE CASCADE,
    UNIQUE (course_id, semester_id)
);
