CREATE TABLE IF NOT EXISTS grading_logs (
    id SERIAL PRIMARY KEY,
    date TIMESTAMP WITH TIME ZONE,
    submission_id INTEGER NOT NULL REFERENCES submissions ON DELETE CASCADE ON UPDATE CASCADE,
    score DOUBLE PRECISION,
    feedback JSONB,
    auth_user_id INTEGER REFERENCES users ON DELETE CASCADE ON UPDATE CASCADE
);
