CREATE TABLE IF NOT EXISTS gradings (
    id SERIAL PRIMARY KEY,
    date TIMESTAMP WITH TIME ZONE,
    submission_id INTEGER NOT NULL REFERENCES submissions ON DELETE CASCADE ON UPDATE CASCADE,
    auth_user_id INTEGER NOT NULL REFERENCES users ON DELETE CASCADE ON UPDATE CASCADE,
    score DOUBLE PRECISION,
    feedback JSONB
);
