CREATE TABLE IF NOT EXISTS question_views (
    id SERIAL PRIMARY KEY,
    question_instance_id INTEGER NOT NULL REFERENCES question_instances ON DELETE CASCADE ON UPDATE CASCADE,
    access_id INTEGER UNIQUE NOT NULL REFERENCES accesses ON DELETE CASCADE ON UPDATE CASCADE,
    open BOOLEAN,
    credit INTEGER
);
