CREATE TABLE IF NOT EXISTS test_scores (
    id SERIAL PRIMARY KEY,
    date TIMESTAMP WITH TIME ZONE,
    points DOUBLE PRECISION,
    max_points DOUBLE PRECISION,
    score_perc INTEGER,
    test_instance_id INTEGER NOT NULL REFERENCES test_instances ON DELETE CASCADE ON UPDATE CASCADE,
    auth_user_id INTEGER NOT NULL REFERENCES users ON DELETE CASCADE ON UPDATE CASCADE
);
