ALTER TABLE tags
ADD COLUMN implicit BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE topics
ADD COLUMN implicit BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE assessment_sets
ADD COLUMN implicit BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE assessment_modules
ADD COLUMN implicit BOOLEAN NOT NULL DEFAULT FALSE;
