CREATE TABLE IF NOT EXISTS authors (
  id BIGSERIAL PRIMARY KEY,
  author_string TEXT,
  UNIQUE (author_string)
);

CREATE TABLE IF NOT EXISTS question_authors (
  id BIGSERIAL PRIMARY KEY,
  question_id BIGINT NOT NULL REFERENCES questions ON UPDATE CASCADE ON DELETE CASCADE,
  author_id BIGINT NOT NULL REFERENCES authors ON UPDATE CASCADE ON DELETE CASCADE
);
