-- Rename the main table
ALTER TABLE course_instance_access_control_overrides 
RENAME TO course_instance_access_control_extensions;

-- Rename the sequence
ALTER SEQUENCE course_instance_access_control_overrides_id_seq 
RENAME TO course_instance_access_control_extensions_id_seq;

-- Rename the primary key constraint
ALTER TABLE course_instance_access_control_extensions 
RENAME CONSTRAINT course_instance_access_control_overrides_pkey 
TO course_instance_access_control_extensions_pkey;

-- Rename the index
ALTER INDEX course_instance_access_control_overrides_course_instance_id_idx 
RENAME TO course_instance_access_control_extensions_course_instance_id_idx;

-- Rename the unique constraint
ALTER TABLE course_instance_access_control_extensions 
RENAME CONSTRAINT course_instance_access_control_overrides_course_instance_id_name_unique 
TO course_instance_access_control_extensions_course_instance_id_name_unique;

-- Rename the foreign key constraint
ALTER TABLE course_instance_access_control_extensions 
RENAME CONSTRAINT course_instance_access_control_override_course_instance_id_fkey 
TO course_instance_access_control_extension_course_instance_id_fkey;

-- Update the foreign key reference in the enrollment overrides table
ALTER TABLE course_instance_access_control_enrollment_overrides 
RENAME COLUMN course_instance_access_control_override_id 
TO course_instance_access_control_extension_id;

-- Update the foreign key constraint in the enrollment overrides table
ALTER TABLE course_instance_access_control_enrollment_overrides 
DROP CONSTRAINT course_instance_access_control_enrollment_overrides_course_instance_access_control_override_id_fkey;

ALTER TABLE course_instance_access_control_enrollment_overrides 
ADD CONSTRAINT course_instance_access_control_enrollment_overrides_course_instance_access_control_extension_id_fkey 
FOREIGN KEY (course_instance_access_control_extension_id) 
REFERENCES course_instance_access_control_extensions(id) 
ON UPDATE CASCADE ON DELETE CASCADE;
