CREATE TABLE IF NOT EXISTS external_image_capture (
  authn_user_id BIGINT NOT NULL REFERENCES authn_users ON DELETE CASCADE ON UPDATE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMPTZ,
  id BIGSERIAL PRIMARY KEY,
  instance_question_id BIGINT NOT NULL REFERENCES instance_questions ON DELETE CASCADE ON UPDATE CASCADE,
  element_uuid TEXT NOT NULL
);
