ALTER TABLE assessment_access_control_rules
RENAME COLUMN after_complete_hide_questions TO after_complete_questions_hidden;

ALTER TABLE assessment_access_control_rules
RENAME COLUMN after_complete_show_questions_again_date_overridden TO after_complete_questions_visible_from_overridden;

ALTER TABLE assessment_access_control_rules
RENAME COLUMN after_complete_show_questions_again_date TO after_complete_questions_visible_from;

ALTER TABLE assessment_access_control_rules
RENAME COLUMN after_complete_hide_questions_again_date_overridden TO after_complete_questions_visible_until_overridden;

ALTER TABLE assessment_access_control_rules
RENAME COLUMN after_complete_hide_questions_again_date TO after_complete_questions_visible_until;

ALTER TABLE assessment_access_control_rules
RENAME COLUMN after_complete_hide_score TO after_complete_score_hidden;

ALTER TABLE assessment_access_control_rules
RENAME COLUMN after_complete_show_score_again_date_overridden TO after_complete_score_visible_from_overridden;

ALTER TABLE assessment_access_control_rules
RENAME COLUMN after_complete_show_score_again_date TO after_complete_score_visible_from;
