parent: base
properties:
  useDatabase:
    default: true
  useEc2MetadataService:
    default: true
  useCloudWatchLogging:
    default: true
  useImagePreloading:
    default: true
  reportLoad:
    default: true
