# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class EPortfolioPage(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'eportfolio_id': 'int',
        'position': 'int',
        'name': 'str',
        'content': 'str',
        'created_at': 'ModelDatetime',
        'updated_at': 'ModelDatetime'
    }

    attribute_map = {
        'id': 'id',
        'eportfolio_id': 'eportfolio_id',
        'position': 'position',
        'name': 'name',
        'content': 'content',
        'created_at': 'created_at',
        'updated_at': 'updated_at'
    }

    def __init__(self, id=None, eportfolio_id=None, position=None, name=None, content=None, created_at=None, updated_at=None, _configuration=None):  # noqa: E501
        """EPortfolioPage - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._id = None
        self._eportfolio_id = None
        self._position = None
        self._name = None
        self._content = None
        self._created_at = None
        self._updated_at = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if eportfolio_id is not None:
            self.eportfolio_id = eportfolio_id
        if position is not None:
            self.position = position
        if name is not None:
            self.name = name
        if content is not None:
            self.content = content
        if created_at is not None:
            self.created_at = created_at
        if updated_at is not None:
            self.updated_at = updated_at

    @property
    def id(self):
        """Gets the id of this EPortfolioPage.  # noqa: E501

        The database ID of the ePortfolio  # noqa: E501

        :return: The id of this EPortfolioPage.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this EPortfolioPage.

        The database ID of the ePortfolio  # noqa: E501

        :param id: The id of this EPortfolioPage.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def eportfolio_id(self):
        """Gets the eportfolio_id of this EPortfolioPage.  # noqa: E501

        The ePortfolio ID to which the entry belongs  # noqa: E501

        :return: The eportfolio_id of this EPortfolioPage.  # noqa: E501
        :rtype: int
        """
        return self._eportfolio_id

    @eportfolio_id.setter
    def eportfolio_id(self, eportfolio_id):
        """Sets the eportfolio_id of this EPortfolioPage.

        The ePortfolio ID to which the entry belongs  # noqa: E501

        :param eportfolio_id: The eportfolio_id of this EPortfolioPage.  # noqa: E501
        :type: int
        """

        self._eportfolio_id = eportfolio_id

    @property
    def position(self):
        """Gets the position of this EPortfolioPage.  # noqa: E501

        The positional order of the entry in the list  # noqa: E501

        :return: The position of this EPortfolioPage.  # noqa: E501
        :rtype: int
        """
        return self._position

    @position.setter
    def position(self, position):
        """Sets the position of this EPortfolioPage.

        The positional order of the entry in the list  # noqa: E501

        :param position: The position of this EPortfolioPage.  # noqa: E501
        :type: int
        """

        self._position = position

    @property
    def name(self):
        """Gets the name of this EPortfolioPage.  # noqa: E501

        The name of the ePortfolio  # noqa: E501

        :return: The name of this EPortfolioPage.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this EPortfolioPage.

        The name of the ePortfolio  # noqa: E501

        :param name: The name of this EPortfolioPage.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def content(self):
        """Gets the content of this EPortfolioPage.  # noqa: E501

        The user entered content of the entry  # noqa: E501

        :return: The content of this EPortfolioPage.  # noqa: E501
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this EPortfolioPage.

        The user entered content of the entry  # noqa: E501

        :param content: The content of this EPortfolioPage.  # noqa: E501
        :type: str
        """

        self._content = content

    @property
    def created_at(self):
        """Gets the created_at of this EPortfolioPage.  # noqa: E501

        The creation timestamp for the ePortfolio  # noqa: E501

        :return: The created_at of this EPortfolioPage.  # noqa: E501
        :rtype: ModelDatetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at):
        """Sets the created_at of this EPortfolioPage.

        The creation timestamp for the ePortfolio  # noqa: E501

        :param created_at: The created_at of this EPortfolioPage.  # noqa: E501
        :type: ModelDatetime
        """

        self._created_at = created_at

    @property
    def updated_at(self):
        """Gets the updated_at of this EPortfolioPage.  # noqa: E501

        The timestamp of the last time any of the ePortfolio attributes changed  # noqa: E501

        :return: The updated_at of this EPortfolioPage.  # noqa: E501
        :rtype: ModelDatetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at):
        """Sets the updated_at of this EPortfolioPage.

        The timestamp of the last time any of the ePortfolio attributes changed  # noqa: E501

        :param updated_at: The updated_at of this EPortfolioPage.  # noqa: E501
        :type: ModelDatetime
        """

        self._updated_at = updated_at

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(EPortfolioPage, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, EPortfolioPage):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, EPortfolioPage):
            return True

        return self.to_dict() != other.to_dict()
