# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class ModuleItemSequenceNode(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'prev': 'ModuleItem',
        'current': 'ModuleItem',
        'next': 'ModuleItem',
        'mastery_path': 'object'
    }

    attribute_map = {
        'prev': 'prev',
        'current': 'current',
        'next': 'next',
        'mastery_path': 'mastery_path'
    }

    def __init__(self, prev=None, current=None, next=None, mastery_path=None, _configuration=None):  # noqa: E501
        """ModuleItemSequenceNode - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._prev = None
        self._current = None
        self._next = None
        self._mastery_path = None
        self.discriminator = None

        if prev is not None:
            self.prev = prev
        if current is not None:
            self.current = current
        if next is not None:
            self.next = next
        if mastery_path is not None:
            self.mastery_path = mastery_path

    @property
    def prev(self):
        """Gets the prev of this ModuleItemSequenceNode.  # noqa: E501

        The previous ModuleItem in the sequence  # noqa: E501

        :return: The prev of this ModuleItemSequenceNode.  # noqa: E501
        :rtype: ModuleItem
        """
        return self._prev

    @prev.setter
    def prev(self, prev):
        """Sets the prev of this ModuleItemSequenceNode.

        The previous ModuleItem in the sequence  # noqa: E501

        :param prev: The prev of this ModuleItemSequenceNode.  # noqa: E501
        :type: ModuleItem
        """

        self._prev = prev

    @property
    def current(self):
        """Gets the current of this ModuleItemSequenceNode.  # noqa: E501

        The ModuleItem being queried  # noqa: E501

        :return: The current of this ModuleItemSequenceNode.  # noqa: E501
        :rtype: ModuleItem
        """
        return self._current

    @current.setter
    def current(self, current):
        """Sets the current of this ModuleItemSequenceNode.

        The ModuleItem being queried  # noqa: E501

        :param current: The current of this ModuleItemSequenceNode.  # noqa: E501
        :type: ModuleItem
        """

        self._current = current

    @property
    def next(self):
        """Gets the next of this ModuleItemSequenceNode.  # noqa: E501

        The next ModuleItem in the sequence  # noqa: E501

        :return: The next of this ModuleItemSequenceNode.  # noqa: E501
        :rtype: ModuleItem
        """
        return self._next

    @next.setter
    def next(self, next):
        """Sets the next of this ModuleItemSequenceNode.

        The next ModuleItem in the sequence  # noqa: E501

        :param next: The next of this ModuleItemSequenceNode.  # noqa: E501
        :type: ModuleItem
        """

        self._next = next

    @property
    def mastery_path(self):
        """Gets the mastery_path of this ModuleItemSequenceNode.  # noqa: E501

        The conditional release rule for the module item, if applicable  # noqa: E501

        :return: The mastery_path of this ModuleItemSequenceNode.  # noqa: E501
        :rtype: object
        """
        return self._mastery_path

    @mastery_path.setter
    def mastery_path(self, mastery_path):
        """Sets the mastery_path of this ModuleItemSequenceNode.

        The conditional release rule for the module item, if applicable  # noqa: E501

        :param mastery_path: The mastery_path of this ModuleItemSequenceNode.  # noqa: E501
        :type: object
        """

        self._mastery_path = mastery_path

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ModuleItemSequenceNode, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ModuleItemSequenceNode):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ModuleItemSequenceNode):
            return True

        return self.to_dict() != other.to_dict()
