# coding: utf-8

"""

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class OutcomeRollup(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'scores': 'OutcomeRollupScore',
        'name': 'str',
        'links': 'OutcomeRollupLinks'
    }

    attribute_map = {
        'scores': 'scores',
        'name': 'name',
        'links': 'links'
    }

    def __init__(self, scores=None, name=None, links=None, _configuration=None):  # noqa: E501
        """OutcomeRollup - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._scores = None
        self._name = None
        self._links = None
        self.discriminator = None

        if scores is not None:
            self.scores = scores
        if name is not None:
            self.name = name
        if links is not None:
            self.links = links

    @property
    def scores(self):
        """Gets the scores of this OutcomeRollup.  # noqa: E501

        an array of OutcomeRollupScore objects  # noqa: E501

        :return: The scores of this OutcomeRollup.  # noqa: E501
        :rtype: OutcomeRollupScore
        """
        return self._scores

    @scores.setter
    def scores(self, scores):
        """Sets the scores of this OutcomeRollup.

        an array of OutcomeRollupScore objects  # noqa: E501

        :param scores: The scores of this OutcomeRollup.  # noqa: E501
        :type: OutcomeRollupScore
        """

        self._scores = scores

    @property
    def name(self):
        """Gets the name of this OutcomeRollup.  # noqa: E501

        The name of the resource for this rollup. For example, the user name.  # noqa: E501

        :return: The name of this OutcomeRollup.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this OutcomeRollup.

        The name of the resource for this rollup. For example, the user name.  # noqa: E501

        :param name: The name of this OutcomeRollup.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def links(self):
        """Gets the links of this OutcomeRollup.  # noqa: E501


        :return: The links of this OutcomeRollup.  # noqa: E501
        :rtype: OutcomeRollupLinks
        """
        return self._links

    @links.setter
    def links(self, links):
        """Sets the links of this OutcomeRollup.


        :param links: The links of this OutcomeRollup.  # noqa: E501
        :type: OutcomeRollupLinks
        """

        self._links = links

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OutcomeRollup, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OutcomeRollup):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OutcomeRollup):
            return True

        return self.to_dict() != other.to_dict()
