# ruff: noqa: F401
# pyright: reportUnusedImport=false
import pytest


def test_external_exports():
    """Checks that no exports have been moved. As time goes on, this list may not be exhaustive."""
    try:
        from prairielearn import (
            ElementTestData,
            PartialScore,
            QuestionData,
            add_files_format_error,
            add_submitted_file,
            all_partial_scores_correct,
            check_answers_names,
            check_attribs,
            clean_identifier_name,
            determine_score_params,
            escape_invalid_string,
            escape_unicode_string,
            from_json,
            full_unidecode,
            get_boolean_attrib,
            get_color_attrib,
            get_enum_attrib,
            get_float_attrib,
            get_integer_attrib,
            get_string_attrib,
            get_unit_registry,
            get_uuid,
            grade_answer_parameterized,
            has_attrib,
            index2key,
            inner_html,
            is_correct_ndarray2D_dd,
            is_correct_ndarray2d_dd,
            is_correct_ndarray2D_ra,
            is_correct_ndarray2d_ra,
            is_correct_ndarray2D_sf,
            is_correct_ndarray2d_sf,
            is_correct_scalar_dd,
            is_correct_scalar_ra,
            is_correct_scalar_sf,
            is_int_json_serializable,
            iter_keys,
            latex_from_2darray,
            load_all_extensions,
            load_extension,
            load_host_script,
            numpy_to_matlab,
            numpy_to_matlab_sf,
            set_all_or_nothing_score_data,
            set_weighted_score_data,
            string_fraction_to_number,
            string_from_2darray,
            string_from_numpy,
            string_partition_first_interval,
            string_partition_outer_interval,
            string_to_2darray,
            string_to_integer,
            string_to_number,
            to_json,
        )
        from prairielearn.colors import (
            PL_COLORS_NAME_MAP,
            PL_COLORS_VALUE_MAP,
            RE_PL_COLORS,
            PrairieLearnColor,
            get_css_color,
        )
        from python_helper_sympy import (
            STANDARD_OPERATORS,
            AssumptionsDictT,
            ASTWhiteListT,
            BaseSympyError,
            CheckAST,
            FunctionNameWithoutArgumentsError,
            HasCommentError,
            HasComplexError,
            HasConflictingFunctionError,
            HasConflictingVariableError,
            HasEscapeError,
            HasFloatError,
            HasInvalidAssumptionError,
            HasInvalidExpressionError,
            HasInvalidFunctionError,
            HasInvalidSymbolError,
            HasInvalidVariableError,
            HasParseError,
            LocalsForEval,
            SympyJson,
            SympyMapT,
            _Constants,
            ast_check_str,
            convert_string_to_sympy,
            convert_string_to_sympy_with_source,
            evaluate,
            evaluate_with_source,
            get_items_list,
            greek_unicode_transform,
            is_sympy_json,
            json_to_sympy,
            point_to_error,
            sympy_check,
            sympy_to_json,
            validate_string_as_sympy,
        )
        from to_precision import (
            eng_notation,
            sci_notation,
            std_notation,
            to_precision,
        )
    except ImportError:
        pytest.fail("One or more exports have been moved.")
