#!/bin/bash
AUTH_UID="<%= authUID %>"
AUTH_NAME="<%= authName %>"
AUTH_DATE="<%= authDate %>"
AUTH_SIGNATURE="<%= authSignature %>"

USER_UID="<%= userUID %>"
QID="<%= qid %>"
QIID="<%= qiid %>"
TIID="<%= tiid %>"

if [ -d "fib" ]; then
    echo -e "\x1b[31m\x1b[4mError\x1b[0m: You have already checked out the problem code."
    echo -e "If you want to replace your code with a clean copy, run \`rm -rf fib\`."
    exit 1
fi

curl -s -H "X-Auth-UID: $AUTH_UID" \
     -H "X-Auth-Name: $AUTH_NAME" \
     -H "X-Auth-Date: $AUTH_DATE" \
     -H "X-Auth-Signature: $AUTH_SIGNATURE" \
     http://localhost:3000/qInstances/$QIID/fib.tar.gz | tar xzf -

cat - fib/Makefile.template << EOF > fib/Makefile
# Begin autogenerated values - do not modify
AUTH_UID = $AUTH_UID
AUTH_NAME = $AUTH_NAME
AUTH_DATE = $AUTH_DATE
AUTH_SIGNATURE = $AUTH_SIGNATURE
USER_UID = $USER_UID
QID = $QID
QIID = $QIID
TIID = $TIID
# End autogenerated values

EOF

rm fib/Makefile.template
echo -e "Problem code has been checked out to `pwd`/fib."
echo -e "Run \`make upload\` to upload your code to PrairieLearn."
