// AUTO-GENERATED by scripts/gen-element-schemas.mts — do not edit by hand.
// Run `make update-element-schemas` to regenerate after adding or removing an
// element schema module under `./elements`.
import { element as plCheckbox } from './elements/pl-checkbox.ts';
import { element as plIntegerInput } from './elements/pl-integer-input.ts';
import { element as plMultipleChoice } from './elements/pl-multiple-choice.ts';
import { element as plNumberInput } from './elements/pl-number-input.ts';
import { element as plOrderBlocks } from './elements/pl-order-blocks.ts';
import { element as plStringInput } from './elements/pl-string-input.ts';
import { element as plSymbolicInput } from './elements/pl-symbolic-input.ts';
import type { ElementSchemaModule } from './types.ts';

export const elementModules: ElementSchemaModule[] = [
  plCheckbox,
  plIntegerInput,
  plMultipleChoice,
  plNumberInput,
  plOrderBlocks,
  plStringInput,
  plSymbolicInput,
];
