name: 'Report bundle sizes'
description: 'Comment bundle size changes on the PR and update the baseline on master pushes'
inputs:
  sizes-path:
    description: 'Path to the sizes.json file produced by the build'
    required: true
  token:
    description: 'GitHub token for commenting and baseline branch operations'
    required: true
runs:
  using: 'node24'
  main: 'dist/index.js'
