name: Upgrade Containers

on:
  workflow_dispatch:
  schedule:
    # At 14:00 (8am CST, 9am CDT) on day-of-month 15.
    - cron: '0 14 15 * *'

jobs:
  upgrade-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1  # v3
        with:
          app-id: ${{ secrets.CI_BOT_APP_ID }}
          private-key: ${{ secrets.CI_BOT_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7

      - name: Set up timestamp
        id: get-timestamp
        run: echo "timestamp=$(date +%Y-%m-%d-%H-%M-%S)" >> "$GITHUB_OUTPUT"

      - name: Upgrade containers
        run: |
          find . -name 'Dockerfile' -exec sed -i "s/ARG CACHEBUST=.*/ARG CACHEBUST=${{ steps.get-timestamp.outputs.timestamp }}/" {} \;

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1
        with:
          token: ${{ steps.generate-token.outputs.token }}
          branch: upgrade-containers-${{ steps.get-timestamp.outputs.timestamp }}
          title: 'Upgrade Docker containers'
          commit-message: 'Bump CACHEBUST value of containers'
          committer: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          body: |
            This PR updates all Dockerfiles with a new `CACHEBUST` value to rebuild the images.
          labels: chore,dependencies,docker
