CREATE TABLE IF NOT EXISTS question_score_logs (
    id BIGSERIAL PRIMARY KEY,
    date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    instance_question_id BIGINT NOT NULL REFERENCES instance_questions ON DELETE CASCADE ON UPDATE CASCADE,
    auth_user_id BIGINT REFERENCES users ON DELETE CASCADE ON UPDATE CASCADE,
    points DOUBLE PRECISION,
    max_points DOUBLE PRECISION,
    score_perc DOUBLE PRECISION
);

ALTER TABLE question_score_logs ALTER COLUMN score_perc SET DATA TYPE DOUBLE PRECISION;

ALTER TABLE question_score_logs ALTER COLUMN id SET DATA TYPE BIGINT;
ALTER TABLE question_score_logs ALTER COLUMN instance_question_id SET DATA TYPE BIGINT;
ALTER TABLE question_score_logs ALTER COLUMN auth_user_id SET DATA TYPE BIGINT;
