CREATE TABLE IF NOT EXISTS tags (
    id BIGSERIAL PRIMARY KEY,
    name varchar(255),
    number INTEGER,
    color varchar(255),
    course_id BIGINT NOT NULL REFERENCES courses ON DELETE CASCADE ON UPDATE CASCADE,
    UNIQUE (name, course_id)
);

ALTER TABLE tags ALTER COLUMN id SET DATA TYPE BIGINT;
ALTER TABLE tags ALTER COLUMN course_id SET DATA TYPE BIGINT;
