CREATE TABLE IF NOT EXISTS variant_view_logs (
    id BIGSERIAL PRIMARY KEY,
    variant_id BIGINT NOT NULL REFERENCES variants ON DELETE CASCADE ON UPDATE CASCADE,
    access_log_id BIGINT UNIQUE NOT NULL REFERENCES access_logs ON DELETE CASCADE ON UPDATE CASCADE,
    open BOOLEAN,
    credit INTEGER
);

ALTER TABLE variant_view_logs ALTER COLUMN id SET DATA TYPE BIGINT;
ALTER TABLE variant_view_logs ALTER COLUMN variant_id SET DATA TYPE BIGINT;
ALTER TABLE variant_view_logs ALTER COLUMN access_log_id SET DATA TYPE BIGINT;
